<a href="https://colab.research.google.com/github/Ayodeji-python/deji/blob/master/income_reconciliation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tabula-py

Collecting tabula-py
  Downloading tabula_py-2.7.0-py3-none-any.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 59.4 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.5.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.22.4)
Collecting distro (from tabula-py)
  Downloading distro-1.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=0.25.3->tabula-py) (1.16.0)
Installing collected packages: distro, tabula-py
Successfully installed distro-1.8.0 tabula-py-2.7.0

In [ ]:
import tabula
import re
tabula.environment_info()

Python version:
    3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
Java version:
    openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu120.04.1, mixed mode, sharing)
tabula-py version: 2.7.0
platform: Linux-5.15.107+-x86_64-with-glibc2.31
uname:
    uname_result(system='Linux', node='41ffbd21e4bf', release='5.15.107+', version='#1 SMP Sat Apr 29 09:15:28 UTC 2023', machine='x86_64')
linux_distribution: ('Ubuntu', '20.04', 'focal')
mac_ver: ('', ('', '', ''), '')

In [ ]:
import tabula
inp1 = (r"Statement20221230.pdf")
inp2 = (r"Statement20230425.pdf")
inp3 = (r"Statement20230630.pdf")
# oup = (r"statement1.csv")
# Read PDF File
# this contain a list
df1 = tabula.read_pdf(inp1, pages = 'all')
df2 = tabula.read_pdf(inp2, pages = 'all')
df3 = tabula.read_pdf(inp3, pages = 'all')

WARNING:tabula.io:Got stderr: Jul 05, 2023 11:07:17 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Jul 05, 2023 11:07:17 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Jul 05, 2023 11:07:17 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 17 fonts
Jul 05, 2023 11:07:17 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
Jul 05, 2023 11:07:17 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats
Jul 05, 2023 11:07:18 PM org.apache.pdfbox.pdmodel.font.PDFont getSpaceWidth
SEVERE: Can't determine the width of the space character, assuming 250
java.lang.NullPointerException
	at org.apache.fontbox.cff.DataInput.hasRemaining(DataInput.java:50)
	at org.apache.fontbox.cff.Type1CharStringParser.parse(Type1CharStringParser.java:80)
	at org.apache.fontbox.cff.Type1CharStringParser.parse(Type1CharStringParser.java:74)
	at org.apache.fontbox.type1.Type1Font.getType1CharString(Type1Font.java:202)
	at org.apache.fontbox.type1.Type1Font.getWidth(Type1Font.java:181)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.getWidthFromFont(PDType1Font.java:471)
	at org.apache.pdfbox.pdmodel.font.PDFont.getSpaceWidth(PDFont.java:552)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.showGlyph(LegacyPDFStreamEngine.java:247)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.showGlyph(PDFStreamEngine.java:805)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.showText(PDFStreamEngine.java:743)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.showTextStrings(PDFStreamEngine.java:652)
	at org.apache.pdfbox.contentstream.operator.text.ShowTextAdjusted.process(ShowTextAdjusted.java:53)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:933)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:514)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:492)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:155)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:144)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:394)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:322)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:269)
	at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:233)
	at technology.tabula.TextStripper.process(TextStripper.java:39)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:27)
	at technology.tabula.PageIterator.next(PageIterator.java:30)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:161)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:124)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:106)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:76)

Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'D' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'D' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'D' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'C' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'C' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'three' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'three' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'three' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'seven' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'seven' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'seven' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 05, 2023 11:07:19 PM org.apache.fontbox.cff.Type1CharStringParser parse

In [ ]:
tabula.convert_into(input_path = inp, output_path = oup,output_format = "csv",pages="all", stream = True)

WARNING:tabula.io:Got stderr: Jul 04, 2023 7:49:01 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
Jul 04, 2023 7:49:01 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats
Jul 04, 2023 7:49:01 PM org.apache.pdfbox.pdmodel.font.PDFont getSpaceWidth
SEVERE: Can't determine the width of the space character, assuming 250
java.lang.NullPointerException
	at org.apache.fontbox.cff.DataInput.hasRemaining(DataInput.java:50)
	at org.apache.fontbox.cff.Type1CharStringParser.parse(Type1CharStringParser.java:80)
	at org.apache.fontbox.cff.Type1CharStringParser.parse(Type1CharStringParser.java:74)
	at org.apache.fontbox.type1.Type1Font.getType1CharString(Type1Font.java:202)
	at org.apache.fontbox.type1.Type1Font.getWidth(Type1Font.java:181)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.getWidthFromFont(PDType1Font.java:471)
	at org.apache.pdfbox.pdmodel.font.PDFont.getSpaceWidth(PDFont.java:552)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.showGlyph(LegacyPDFStreamEngine.java:247)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.showGlyph(PDFStreamEngine.java:805)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.showText(PDFStreamEngine.java:743)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.showTextStrings(PDFStreamEngine.java:652)
	at org.apache.pdfbox.contentstream.operator.text.ShowTextAdjusted.process(ShowTextAdjusted.java:53)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:933)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:514)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:492)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:155)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:144)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:394)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:322)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:269)
	at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:233)
	at technology.tabula.TextStripper.process(TextStripper.java:39)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:27)
	at technology.tabula.PageIterator.next(PageIterator.java:30)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:161)
	at technology.tabula.CommandLineApp.extractFileInto(CommandLineApp.java:139)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:129)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:106)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:76)

Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'M' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'R' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'S' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'D' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'D' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'D' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'L' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'E' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'N' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'one' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'eight' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'J' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'C' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'C' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'K' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'B' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'P' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'T' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'H' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'three' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'three' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'three' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'seven' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'seven' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'seven' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'four' of font Helvetica
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'asterisk' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'numbersign' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse
WARNING: CALLSUBR is ignored, operand: 4, subrs.size(): 0 in glyph 'numbersign' of font Arial
Jul 04, 2023 7:49:02 PM org.apache.fontbox.cff.Type1CharStringParser parse

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_all4_1 = pd.DataFrame(columns=['Unnamed: 0', 'Unnamed: 1', 'Account Number', '06 3171 11277956'])
df_all6_1 = pd.DataFrame(columns=['Date', 'Transaction', 'Debit', 'Unnamed: 0','Credit','Balance'])
df_all4_2 = pd.DataFrame(columns=['Unnamed: 0', 'Unnamed: 1', 'Account Number', '06 3171 11277956'])
df_all6_2_1 = pd.DataFrame(columns=['Date Transaction', 'Unnamed: 0', 'Debit', 'Unnamed: 1', 'Credit', 'Balance'])
df_all6_2_2 = pd.DataFrame(columns=['Date', 'Transaction', 'Debit', 'Unnamed: 0','Credit','Balance'])
df_all4_3 = pd.DataFrame(columns=['Unnamed: 0', 'Unnamed: 1', 'Account Number', '06 3171 11277956'])
df_all6_3 = pd.DataFrame(columns=['Date Transaction', 'Unnamed: 0', 'Debit', 'Unnamed: 1', 'Credit','Balance'])

In [ ]:
for i in range(len(df1)):
  if df1[i].shape[1] == 4:
    print(i)
    # print(df1[i].shape)
    df_all4_1 = pd.concat([df_all4_1, df1[i]], ignore_index=True)
  else:
    print(i)
    print(df1[i].shape)
    print(df1[i].columns)
    #ok to concatenate as column headers are in same order ['Date', 'Transaction', 'Debit', 'Unnamed: 0', 'Credit', 'Balance']
    df_all6_1 = pd.concat([df_all6_1, df1[i]], ignore_index=True)

for k in range(len(df2)):
  if df2[k].shape[1] == 4:
    print(k)
    # print(df2[k].shape)
    df_all4_2 = pd.concat([df_all4_2, df2[k]], ignore_index=True)
  else:
    print(k)
    print(df2[k].shape)
    print(df2[k].columns)
    #Not ok concatenate as column headers are in not same order
    #add df2[0] to df_all6_3 ['Date Transaction', 'Unnamed: 0', 'Debit', 'Unnamed: 1', 'Credit', 'Balance']
    #add df2[1] to df_all6_1 ['Date', 'Transaction', 'Debit', 'Unnamed: 0', 'Credit', 'Balance']
    # df_all6_2 = pd.concat([df_all6_2, df2[k]], ignore_index=True)

for j in range(len(df3)):
  if df3[j].shape[1] == 4:
    print(j)
    # print(df3[j].shape)
    df_all4_3 = pd.concat([df_all4_3, df3[j]], ignore_index=True)
  else:
    print(j)
    print(df3[j].shape)
    print(df3[j].columns)
    #ok to concatenate as column headers are in same order
    #['Date Transaction', 'Unnamed: 0', 'Debit', 'Unnamed: 1', 'Credit','Balance']
    df_all6_3 = pd.concat([df_all6_3, df3[j]], ignore_index=True)

0
(24, 6)
Index(['Date', 'Transaction', 'Debit', 'Unnamed: 0', 'Credit', 'Balance'], dtype='object')
1
(43, 6)
Index(['Date', 'Transaction', 'Debit', 'Unnamed: 0', 'Credit', 'Balance'], dtype='object')
2
3
4
5
6
7
8
9
10
11
12
13
14
0
(19, 6)
Index(['Date Transaction', 'Unnamed: 0', 'Debit', 'Unnamed: 1', 'Credit',
       'Balance'],
      dtype='object')
1
(43, 6)
Index(['Date', 'Transaction', 'Debit', 'Unnamed: 0', 'Credit', 'Balance'], dtype='object')
2
3
4
5
6
7
8
9
10
0
(24, 6)
Index(['Date Transaction', 'Unnamed: 0', 'Debit', 'Unnamed: 1', 'Credit',
       'Balance'],
      dtype='object')
1
(44, 6)
Index(['Date Transaction', 'Unnamed: 0', 'Debit', 'Unnamed: 1', 'Credit',
       'Balance'],
      dtype='object')
2
3
4
5
6
7

In [ ]:
df_all4 = pd.concat([df_all4_1, df_all4_2,df_all4_3], ignore_index=True)
df_all4

,Unnamed: 0,Unnamed: 1,Account Number,06 3171 11277956
0,Date,Transaction,Debit Credit,Balance
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
2,NaN,Card xx6241,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR"
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN
1486,NaN,Card xx6241,NaN,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR"
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR"

In [ ]:
df_all6_1_1 = pd.concat([ df_all6_1 , df2[1]], ignore_index=True)
df_all6_1_1

,Date,Transaction,Debit,Unnamed: 0,Credit,Balance
0,01 Jul,2022 OPENING BALANCE,NaN,NaN,NaN,"$6,622.66 CR"
1,01 Jul,Salary 9D Care,NaN,NaN,NaN,NaN
2,NaN,9D Care,NaN,NaN,$275.22,"$6,897.88 CR"
3,04 Jul,Direct Credit 074806 BUPA_CLM_CR-0407,NaN,NaN,NaN,NaN
4,NaN,C57037079 07876718,NaN,NaN,$100.60,"$6,998.48 CR"
...,...,...,...,...,...,...
105,22 Jan,WPNP PTY LTD CommBank app BPAY 3,NaN,NaN,NaN,NaN
106,NaN,1635571282 rent,"1,651.00",$,NaN,"$1,957.02 CR"
107,24 Jan,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN
108,NaN,Card xx5698,NaN,NaN,NaN,NaN
109,NaN,Value Date: 22/01/2023,32.70,$,NaN,"$1,924.32 CR"

In [ ]:
df_all6_1_2 = pd.concat([ df_all6_3 , df2[0]], ignore_index=True)
df_all6_1_2

,Date Transaction,Unnamed: 0,Debit,Unnamed: 1,Credit,Balance
0,26 Apr 2023 OPENING BALANCE,NaN,NaN,NaN,NaN,"$4,942.30 CR"
1,26 Apr Fast Transfer From A A LADEINDE,NaN,NaN,NaN,NaN,NaN
2,move balance,NaN,NaN,NaN,$0.94,"$4,943.24 CR"
3,26 Apr Salary YNA,NaN,NaN,NaN,NaN,NaN
4,Payroll,NaN,NaN,NaN,"$1,131.32","$6,074.56 CR"
...,...,...,...,...,...,...
82,10 Jan VICROADS CommBank app BPAY 2,NaN,NaN,NaN,NaN,NaN
83,528671080015065,NaN,864.40,$,NaN,"$3,315.71 CR"
84,10 Jan Direct Debit 066429 Linkt Melbourne,NaN,NaN,NaN,NaN,NaN
85,70746973-754237184,NaN,14.94,$,NaN,"$3,300.77 CR"
86,11 Jan PROUDS 132 MULGRAVE AU,NaN,71.90,$,NaN,"$3,228.87 CR"

In [ ]:
df_all4

,Unnamed: 0,Unnamed: 1,Account Number,06 3171 11277956
0,Date,Transaction,Debit Credit,Balance
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
2,NaN,Card xx6241,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR"
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN
1486,NaN,Card xx6241,NaN,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR"
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR"

In [ ]:
df_all4copy = pd.DataFrame(df_all4)
df_all4copy

,Unnamed: 0,Unnamed: 1,Account Number,06 3171 11277956
0,Date,Transaction,Debit Credit,Balance
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
2,NaN,Card xx6241,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR"
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN
1486,NaN,Card xx6241,NaN,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR"
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR"

In [ ]:
for col in df_all4copy.columns:
    print(col)

Unnamed: 0
Unnamed: 1
Account Number
06 3171 11277956

In [ ]:
df_all4copy_renamed = df_all4copy.rename(columns={"Unnamed: 0": "Date", "Unnamed: 1": "Transaction Details", "Account Number": "Debit Credit", "06 3171 11277956":"Balance"})

In [ ]:
df_all4copy_renamed

,Date,Transaction Details,Debit Credit,Balance
0,Date,Transaction,Debit Credit,Balance
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
2,NaN,Card xx6241,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR"
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN
...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN
1486,NaN,Card xx6241,NaN,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR"
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR"

In [ ]:
#dropping duplicated rows containing header info
df_all4copy_renamed = df_all4copy_renamed[~((df_all4copy_renamed['Date'] == 'Date') | (df_all4copy_renamed['Date'] =='Date Transaction')) ]

In [ ]:
df_all4copy_renamed

        Date                   Transaction Details Debit Credit        Balance
1     19 Jul    MON HLTH CLAY CPARK CLAYTON VI AUS          NaN            NaN
2        NaN                           Card xx6241          NaN            NaN
3        NaN                Value Date: 15/07/2022      11.05 $  $10,467.01 CR
4     20 Jul    MON HLTH CLAY CPARK CLAYTON VI AUS          NaN            NaN
5        NaN                           Card xx6241          NaN            NaN
...      ...                                   ...          ...            ...
1485  30 Jun       WOOLWORTHS 3130 MULGRAVE AU AUS          NaN            NaN
1486     NaN                           Card xx6241          NaN            NaN
1487     NaN                Value Date: 28/06/2023      54.39 (   $4,257.88 CR
1488  30 Jun  Direct Debit 348045 AGL SALES PTY LT          NaN            NaN
1489     NaN                          520010979544     109.12 (   $4,148.76 CR

[1462 rows x 4 columns]

In [ ]:
debit_patterns = ['^\d{1,3}(?:,\d{3})*(?:\.\d{2})?\s\$$','^\d{1,3}(?:,\d{3})*(?:\.\d{2})?\s\($']

In [ ]:
# df_all4copy_renamed['Debit Credit'].str.contains('|'.join(debit_patterns))

1         NaN
2         NaN
3        True
4         NaN
5         NaN
        ...
1485      NaN
1486      NaN
1487     True
1488      NaN
1489    False
Name: Debit Credit, Length: 1475, dtype: object

In [ ]:
#extracting debit figures
df_all4copy_renamed["Debit"] = df_all4copy_renamed.loc[df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'].str.contains('|'.join(debit_patterns)) == True].index.tolist()]['Debit Credit']
df_all4copy_renamed

<ipython-input-57-28b2f1d9eccb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all4copy_renamed["Debit"] = df_all4copy_renamed.loc[df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'].str.contains('|'.join(debit_patterns)) == True].index.tolist()]['Debit Credit']

,Date,Transaction Details,Debit Credit,Balance,Debit
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN
2,NaN,Card xx6241,NaN,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN
5,NaN,Card xx6241,NaN,NaN,NaN
...,...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN,NaN
1486,NaN,Card xx6241,NaN,NaN,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR",54.39 (
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR",109.12 (

In [ ]:
#extracting debit figures
df_all4copy_renamed["Credit"] = df_all4copy_renamed.loc[df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'].str.startswith('$') == True].index.tolist()]['Debit Credit']
df_all4copy_renamed

<ipython-input-58-15fa6113ba01>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all4copy_renamed["Credit"] = df_all4copy_renamed.loc[df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'].str.startswith('$') == True].index.tolist()]['Debit Credit']

,Date,Transaction Details,Debit Credit,Balance,Debit,Credit
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN
2,NaN,Card xx6241,NaN,NaN,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $,NaN
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN
5,NaN,Card xx6241,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN,NaN,NaN
1486,NaN,Card xx6241,NaN,NaN,NaN,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR",54.39 (,NaN
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN,NaN,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR",109.12 (,NaN

In [ ]:
# df_all4copy_renamed["Credit"]

1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
       ...
1485    NaN
1486    NaN
1487    NaN
1488    NaN
1489    NaN
Name: Credit, Length: 1475, dtype: object

In [ ]:
# df_all4copy_renamed[~df_all4copy_renamed["Debit"].isnull()]

# df_all4copy_renamed['Debit Credit']

,Date,Transaction Details,Debit Credit,Balance,Debit,Credit
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $,NaN
6,NaN,Value Date: 18/07/2022,11.05 $,"$10,455.96 CR",11.05 $,NaN
9,NaN,Value Date: 18/07/2022,19.09 $,"$10,436.87 CR",19.09 $,NaN
20,NaN,Value Date: 20/07/2022,12.00 $,"$10,582.43 CR",12.00 $,NaN
25,NaN,Value Date: 22/07/2022,60.00 $,"$10,756.93 CR",60.00 $,NaN
...,...,...,...,...,...,...
1466,NaN,Value Date: 25/06/2023,28.00 (,"$4,183.88 CR",28.00 (,NaN
1470,NaN,Value Date: 26/06/2023,10.34 (,"$4,063.54 CR",10.34 (,NaN
1476,NaN,Value Date: 25/06/2023,20.14 (,"$4,041.40 CR",20.14 (,NaN
1484,29 Jun,AMAYSIM MOBILE PTY LTD,10.00 (,"$4,312.27 CR",10.00 (,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR",54.39 (,NaN

In [ ]:
# df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'].str.endswith(('$') or ('(') ) == True].index.tolist()] = 0

<ipython-input-115-b92d52507821>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'][df_all4copy_renamed['Debit Credit'].str.endswith(('$')) == True].index.tolist()] = 0

In [ ]:
df_all4copy_renamed.to_csv('output1.csv', index=False)

In [ ]:
df_all4copy_renamed_copy = df_all4copy_renamed.copy()

In [ ]:
df_all4copy_renamed.drop(df_all4copy_renamed.columns, axis=1)

Empty DataFrame
Columns: []
Index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, ...]

[1462 rows x 0 columns]

In [ ]:
df_all4copy_renamed = df_all4copy_renamed_copy

In [ ]:
df_all4copy_renamed_copy

,Date,Transaction Details,Debit Credit,Balance,Debit,Credit,New_Date,Details
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,19 Jul,NaN
2,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,nan Card xx6241
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $,NaN,NaN,nan Value Date: 15/07/2022
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,20 Jul,NaN
5,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,nan Card xx6241
...,...,...,...,...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN,NaN,NaN,30 Jun,NaN
1486,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,nan Card xx6241
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR",54.39 (,NaN,NaN,nan Value Date: 28/06/2023
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN,NaN,NaN,30 Jun,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR",109.12 (,NaN,NaN,nan 520010979544

In [ ]:
# used to split the values under date column e.g 02 Aug WOOLWORTHS 3940 CRANBOURNE W AU AUS
x = df_all4copy_renamed['Date'].str.extract(r'(\d+\s\w+)\s(.+)')
x[~x[0].isnull()].head(50)

          0                                         1
55   29 Jul                            Salary 9D Care
57   30 Jul        FINES VICTORIA CommBank app BPAY 4
59   30 Jul                 UNITED CLAYTON CLAYTON AU
60   01 Aug             Direct Debit 314011 AGL TELCO
62   02 Aug     NovaPharmacy Waverley Mulgrave VI AUS
65   02 Aug           ALLIANZ INSURE C6 SYDNEY NS AUS
68   02 Aug       WOOLWORTHS 3940 CRANBOURNE W AU AUS
71   04 Aug  SKVORTSOV, ALEKSEI AL Noble Park No VI A
74   04 Aug       WOOLWORTHS 3130 WAVERLEY GDNS AU AU
77   04 Aug                    Salary Nextt Health PL
79   06 Aug   MOORABBIN CAR PARKING Bentleigh Eas AUS
82   07 Aug           Transfer to xx7964 CommBank app
84   09 Aug       WOOLWORTHS 3940 CRANBOURNE W AU AUS
87   09 Aug           PIERRE COLLET MOTORS BURWOOD AU
89   10 Aug    COLES EXPRESS 6805 NOBLE PARK N AU AUS
92   10 Aug                   Salary MONASH UNIVERSIT
94   10 Aug                   Salary MONASH UNIVERSIT
96   10 Aug      Direct Debit 518073 Ezypay Pty Ltd C
98   10 Aug                        Salary HammondCare
100  11 Aug         BETTER CHOICE BURWOOD BURWOOD AUS
103  11 Aug            COLES 0584 BURWOOD EAST AU AUS
106  11 Aug          Direct Credit 621009 SmartSalary
109  11 Aug                            Salary 9D Care
111  13 Aug     SURUR AFRICAN SUPER NOBLE PARK VI AUS
114  13 Aug   AMBULANCE VIC ACCTS CommBank app BPAY 2
116  15 Aug        ALDI STORES - WAVERLEY MULGRAVE AU
118  15 Aug      Direct Debit 518073 Performance Educ
120  15 Aug      Direct Debit 507533 SOUTH EAST WATER
122  16 Aug          AA MULGRAVE 3222 MULGRAVE VI AUS
125  17 Aug                 KFC OAKLEIGH OAKLEIGH AUS
128  17 Aug                 KFC OAKLEIGH OAKLEIGH AUS
131  17 Aug     Direct Credit 074806 BUPA_CLM_CR-1708
133  18 Aug  LIBERTY JACKSONS RD NOBLE PARK NO VI AUS
136  18 Aug                    Salary Nextt Health PL
138  18 Aug       Direct Debit 066429 Linkt Melbourne
140  19 Aug          WPNP PTY LTD NetBank BPAY 304303
142  19 Aug      Direct Credit 141000 ELEVATE SUPPORT
144  24 Aug                   Salary MONASH UNIVERSIT
146  24 Aug                   Salary MONASH UNIVERSIT
148  24 Aug       Direct Debit 026160 RACV Assistance
150  24 Aug                        Salary HammondCare
152  25 Aug          Direct Credit 621009 SmartSalary
154  26 Aug  POST BURWOOD EAST LPBU BURWOOD EAST CA A
157  26 Aug             SHOEFIT SHOES MULGRAVE VI AUS
160  26 Aug            KMART 1001 BURWOOD EAST AU AUS
164  26 Aug            COLES 0584 BURWOOD EAST AU AUS
167  26 Aug                            Salary 9D Care
169  26 Aug           Transfer to xx7964 CommBank app
171  30 Aug  LIBERTY JACKSONS RD NOBLE PARK NO VI AUS
174  30 Aug  LIBERTY JACKSONS RD NOBLE PARK NO VI AUS

In [ ]:
# used to split the values under date column e.g 02 Aug WOOLWORTHS 3940 CRANBOURNE W AU AUS used it to create new columns 'New_Date', 'Details'
df_all4copy_renamed[['New_Date', 'Details']] = df_all4copy_renamed['Date'].str.extract(r'(\d+\s\w+)\s(.+)')

In [ ]:
df_all4copy_renamed[df_all4copy_renamed['Details'].isnull()]

,Date,Transaction Details,Debit Credit,Balance,Debit,Credit,New_Date,Details
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $,NaN,NaN,NaN
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1485,30 Jun,WOOLWORTHS 3130 MULGRAVE AU AUS,NaN,NaN,NaN,NaN,NaN,NaN
1486,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
1487,NaN,Value Date: 28/06/2023,54.39 (,"$4,257.88 CR",54.39 (,NaN,NaN,NaN
1488,30 Jun,Direct Debit 348045 AGL SALES PTY LT,NaN,NaN,NaN,NaN,NaN,NaN
1489,NaN,520010979544,109.12 (,"$4,148.76 CR",109.12 (,NaN,NaN,NaN

In [ ]:
df_all4copy_renamed.isnull().sum()

Date                    413
Transaction Details     683
Debit Credit            779
Balance                 779
Debit                   947
Credit                 1294
New_Date               1142
Details                1142
dtype: int64

In [ ]:
#obtained dates with the (\d+\s\w+) format from the dates column, intended to fill the New_Date Column
df_all4copy_renamed['Date'][(df_all4copy_renamed['Date'].str.contains(r'(\d+\s\w+)') == True)]

<ipython-input-89-5190a33ca538>:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_all4copy_renamed['Date'][(df_all4copy_renamed['Date'].str.contains(r'(\d+\s\w+)') == True)]

1       19 Jul
4       20 Jul
7       20 Jul
10      20 Jul
11      20 Jul
         ...
1481    28 Jun
1483    29 Jun
1484    29 Jun
1485    30 Jun
1488    30 Jun
Name: Date, Length: 697, dtype: object

In [ ]:
#obtained dates with the (\d+\s\w+) format from the dates column, used it to fill the null values in the New_Date Column
df_all4copy_renamed['New_Date']= df_all4copy_renamed['New_Date'].fillna(df_all4copy_renamed['Date'][df_all4copy_renamed['Date'].str.contains(r'(\d{2}\s\w{3})') == True])

<ipython-input-91-d6569107b802>:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_all4copy_renamed['New_Date']= df_all4copy_renamed['New_Date'].fillna(df_all4copy_renamed['Date'][df_all4copy_renamed['Date'].str.contains(r'(\d{2}\s\w{3})') == True])

In [ ]:
df_all4copy_renamed.isnull().sum()

Date                    413
Transaction Details     683
Debit Credit            779
Balance                 779
Debit                   947
Credit                 1294
New_Date                767
Details                1142
dtype: int64

In [ ]:
df_all4copy_renamed.head(55)

,Date,Transaction Details,Debit Credit,Balance,Debit,Credit,New_Date,Details
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,19 Jul,NaN
2,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $,NaN,NaN,NaN
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,20 Jul,NaN
5,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Value Date: 18/07/2022,11.05 $,"$10,455.96 CR",11.05 $,NaN,NaN,NaN
7,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,20 Jul,NaN
8,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Value Date: 18/07/2022,19.09 $,"$10,436.87 CR",19.09 $,NaN,NaN,NaN
10,20 Jul,HENRYS MERCATO WAVER MULGRAVE AU,8.37 $,"$10,428.50 CR",8.37 $,NaN,20 Jul,NaN
11,20 Jul,Direct Debit 518073 Performance Educ,NaN,NaN,NaN,NaN,20 Jul,NaN
12,NaN,EZYPAYID 323911303,901.32 $,"$9,527.18 CR",901.32 $,NaN,NaN,NaN
13,21 Jul,Salary Nextt Health PL,NaN,NaN,NaN,NaN,21 Jul,NaN
14,NaN,10207717/07/2022,"$1,076.25","$10,603.43 CR",NaN,"$1,076.25",NaN,NaN
15,22 Jul,COLES 0553 MULGRAVE AU AUS,NaN,NaN,NaN,NaN,22 Jul,NaN
16,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Value Date: 20/07/2022,9.00 $,"$10,594.43 CR",9.00 $,NaN,NaN,NaN
18,22 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN,22 Jul,NaN
19,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Value Date: 20/07/2022,12.00 $,"$10,582.43 CR",12.00 $,NaN,NaN,NaN
21,22 Jul,Direct Credit 141000 ELEVATE SUPPORT,NaN,NaN,NaN,NaN,22 Jul,NaN
22,NaN,PAY CHEQUE,$234.50,"$10,816.93 CR",NaN,$234.50,NaN,NaN
23,23 Jul,COSTCO FUEL MOORABBIN MOORABBIN AIR AUS,NaN,NaN,NaN,NaN,23 Jul,NaN
24,NaN,Card xx5698,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Value Date: 22/07/2022,60.00 $,"$10,756.93 CR",60.00 $,NaN,NaN,NaN
26,23 Jul,LIBERTY JACKSONS RD NOBLE PARK NO VI AUS,NaN,NaN,NaN,NaN,23 Jul,NaN
27,NaN,Card xx5698,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Value Date: 21/07/2022,99.57 $,"$10,657.36 CR",99.57 $,NaN,NaN,NaN
29,23 Jul,SURUR AFRICAN SUPER NOBLE PARK VI AUS,NaN,NaN,NaN,NaN,23 Jul,NaN
30,NaN,Card xx5698,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Value Date: 21/07/2022,56.00 $,"$10,601.36 CR",56.00 $,NaN,NaN,NaN
32,25 Jul,Direct Debit 026160 RACV Assistance,NaN,NaN,NaN,NaN,25 Jul,NaN
33,NaN,RACV-0000-10441487,16.83 $,"$10,584.53 CR",16.83 $,NaN,NaN,NaN
34,25 Jul,Direct Debit 026160 RACV Assistance,NaN,NaN,NaN,NaN,25 Jul,NaN
35,NaN,RACV-0000-10443085,18.89 $,"$10,565.64 CR",18.89 $,NaN,NaN,NaN
36,25 Jul,Direct Credit 074806 BUPA_CREDIT-2507,NaN,NaN,NaN,NaN,25 Jul,NaN
37,NaN,B46484796 08033681,$100.60,"$10,666.24 CR",NaN,$100.60,NaN,NaN
38,26 Jul,HENRYS MERCATO WAVER MULGRAVE AU,20.15 $,"$10,646.09 CR",20.15 $,NaN,26 Jul,NaN
39,26 Jul,ALDI STORES - WAVERLEY MULGRAVE AU,NaN,NaN,NaN,NaN,26 Jul,NaN
40,NaN,Card xx6241,18.36 $,"$10,627.73 CR",18.36 $,NaN,NaN,NaN
41,27 Jul,Salary MONASH UNIVERSIT,NaN,NaN,NaN,NaN,27 Jul,NaN
42,NaN,SALARY 01163158,"$1,226.56","$11,854.29 CR",NaN,"$1,226.56",NaN,NaN
43,27 Jul,Salary Yooralla,NaN,NaN,NaN,NaN,27 Jul,NaN
44,NaN,0009308,$171.77,"$12,026.06 CR",NaN,$171.77,NaN,NaN
45,27 Jul,Direct Credit 621009 SmartSalary,NaN,NaN,NaN,NaN,27 Jul,NaN
46,NaN,GroupedSS,$508.32,"$12,534.38 CR",NaN,$508.32,NaN,NaN
47,27 Jul,Salary HammondCare,NaN,NaN,NaN,NaN,27 Jul,NaN
48,NaN,20052,$492.70,"$13,027.08 CR",NaN,$492.70,NaN,NaN
49,28 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN,28 Jul,NaN
50,NaN,Card xx6241,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,Value Date: 26/07/2022,49.90 $,"$12,977.18 CR",49.90 $,NaN,NaN,NaN
52,28 Jul,Direct Credit 621009 SmartSalary,NaN,NaN,NaN,NaN,28 Jul,NaN
53,NaN,GroupedSS,$757.13,"$13,734.31 CR",NaN,$757.13,NaN,NaN
55,29 Jul Salary 9D Care,NaN,NaN,NaN,NaN,NaN,29 Jul,Salary 9D Care
56,9D Care,NaN,"$1,546.34","$15,280.65 CR",NaN,"$1,546.34",NaN,NaN

In [ ]:
#extracting those text under the date column to see if we can use it to fill the nanin the details column
df_all4copy_renamed['Date'][df_all4copy_renamed['Date'].str.contains(r'(\d+\s\w+)') == False]

<ipython-input-94-3ce342b7abaa>:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_all4copy_renamed['Date'][df_all4copy_renamed['Date'].str.contains(r'(\d+\s\w+)') == False]

56                     9D Care
61            PAYWAY3264677184
63                 Card xx5698
64      Value Date: 31/07/2022
66                 Card xx5698
                 ...
1320                   0009308
1322                   Payroll
1324                 GroupedSS
1326               Card xx6241
1327    Value Date: 30/05/2023
Name: Date, Length: 352, dtype: object

In [ ]:
#Filling the nan in the details column with the text extracted from the date column
df_all4copy_renamed['Details']= df_all4copy_renamed['Details'].fillna(df_all4copy_renamed['Date'][df_all4copy_renamed['Date'].str.contains(r'(\d+\s\w+)') == False])

<ipython-input-95-3164f3cc3205>:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_all4copy_renamed['Details']= df_all4copy_renamed['Details'].fillna(df_all4copy_renamed['Date'][df_all4copy_renamed['Date'].str.contains(r'(\d+\s\w+)') == False])

In [ ]:
df_all4copy_renamed.isnull().sum()

Date                    413
Transaction Details     683
Debit Credit            779
Balance                 779
Debit                   947
Credit                 1294
New_Date                767
Details                 790
dtype: int64

In [ ]:
#Filling the remaining nan in the details column with the text extracted from the Transaction Details column
df_all4copy_renamed['Details']= df_all4copy_renamed['Details'].fillna(df_all4copy_renamed["Transaction Details"])

In [ ]:
df_all4copy_renamed.isnull().sum()

Date                    413
Transaction Details     683
Debit Credit            779
Balance                 779
Debit                   947
Credit                 1294
New_Date                767
Details                  11
dtype: int64

In [ ]:
#Filling the remaining 11 nans in the details column with the text obtained by concatenating from the values in New_Date column with the nan in the details column
df_all4copy_renamed['Details']= df_all4copy_renamed['Details'].fillna(df_all4copy_renamed[df_all4copy_renamed['Details'].isnull()]['Date'])

In [ ]:
df_all4copy_renamed[df_all4copy_renamed['Details'].isnull()]['Date']

58            2217209066 fine
115     69115681012 Ambulance
132        C46484796 08208214
141           1635571282 rent
239           1635571282 rent
534        DT.15h2j2 57598870
558           1635571282 rent
568        B46484796 08914640
659        DT.18n600 67449355
666           1635571282 rent
1214       DT.1pg9t8 27021064
Name: Date, dtype: object

In [ ]:
df_all4copy_renamed.isnull().sum()

Date                    413
Transaction Details     683
Debit Credit            779
Balance                 779
Debit                   947
Credit                 1294
New_Date                767
Details                   0
dtype: int64

In [ ]:

# rows_to_concatenate = df_all4copy_renamed['New_Date'][~(df_all4copy_renamed['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)].index.tolist()
# columns_to_concatenate = ['New_Date', 'Details']

# df_all4copy_renamed['Details'] = df_all4copy_renamed.loc[rows_to_concatenate][columns_to_concatenate].apply(lambda x: ' '.join(map(str, x)), axis=1)

<ipython-input-79-fe4ff217e601>:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  rows_to_concatenate = df_all4copy_renamed['New_Date'][~(df_all4copy_renamed['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)].index.tolist()

In [ ]:
#Filling new date column with the dates in the prior cells for same transaction
df_all4copy_renamed.New_Date = df_all4copy_renamed.New_Date.ffill()

In [ ]:
df_all4copy_renamed['New_Date'][~(df_all4copy_renamed['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)]

<ipython-input-105-92ce72f1f6a4>:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_all4copy_renamed['New_Date'][~(df_all4copy_renamed['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)]

58             2217209066 fine
115      69115681012 Ambulance
132         C46484796 08208214
141            1635571282 rent
239            1635571282 rent
501     527831105733940 AURION
558            1635571282 rent
568         B46484796 08914640
659         DT.18n600 67449355
666            1635571282 rent
1303                  5698 GBP
1304                  5698 GBP
1308                  5698 GBP
1309                  5698 GBP
Name: New_Date, dtype: object

In [ ]:
df_all4copy_renamed. head(50)

,Date,Transaction Details,Debit Credit,Balance,Debit,Credit,New_Date,Details
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS
2,NaN,Card xx6241,NaN,NaN,NaN,NaN,19 Jul,Card xx6241
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $,NaN,19 Jul,Value Date: 15/07/2022
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS
5,NaN,Card xx6241,NaN,NaN,NaN,NaN,20 Jul,Card xx6241
6,NaN,Value Date: 18/07/2022,11.05 $,"$10,455.96 CR",11.05 $,NaN,20 Jul,Value Date: 18/07/2022
7,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS
8,NaN,Card xx6241,NaN,NaN,NaN,NaN,20 Jul,Card xx6241
9,NaN,Value Date: 18/07/2022,19.09 $,"$10,436.87 CR",19.09 $,NaN,20 Jul,Value Date: 18/07/2022
10,20 Jul,HENRYS MERCATO WAVER MULGRAVE AU,8.37 $,"$10,428.50 CR",8.37 $,NaN,20 Jul,HENRYS MERCATO WAVER MULGRAVE AU
11,20 Jul,Direct Debit 518073 Performance Educ,NaN,NaN,NaN,NaN,20 Jul,Direct Debit 518073 Performance Educ
12,NaN,EZYPAYID 323911303,901.32 $,"$9,527.18 CR",901.32 $,NaN,20 Jul,EZYPAYID 323911303
13,21 Jul,Salary Nextt Health PL,NaN,NaN,NaN,NaN,21 Jul,Salary Nextt Health PL
14,NaN,10207717/07/2022,"$1,076.25","$10,603.43 CR",NaN,"$1,076.25",21 Jul,10207717/07/2022
15,22 Jul,COLES 0553 MULGRAVE AU AUS,NaN,NaN,NaN,NaN,22 Jul,COLES 0553 MULGRAVE AU AUS
16,NaN,Card xx6241,NaN,NaN,NaN,NaN,22 Jul,Card xx6241
17,NaN,Value Date: 20/07/2022,9.00 $,"$10,594.43 CR",9.00 $,NaN,22 Jul,Value Date: 20/07/2022
18,22 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN,22 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU
19,NaN,Card xx6241,NaN,NaN,NaN,NaN,22 Jul,Card xx6241
20,NaN,Value Date: 20/07/2022,12.00 $,"$10,582.43 CR",12.00 $,NaN,22 Jul,Value Date: 20/07/2022
21,22 Jul,Direct Credit 141000 ELEVATE SUPPORT,NaN,NaN,NaN,NaN,22 Jul,Direct Credit 141000 ELEVATE SUPPORT
22,NaN,PAY CHEQUE,$234.50,"$10,816.93 CR",NaN,$234.50,22 Jul,PAY CHEQUE
23,23 Jul,COSTCO FUEL MOORABBIN MOORABBIN AIR AUS,NaN,NaN,NaN,NaN,23 Jul,COSTCO FUEL MOORABBIN MOORABBIN AIR AUS
24,NaN,Card xx5698,NaN,NaN,NaN,NaN,23 Jul,Card xx5698
25,NaN,Value Date: 22/07/2022,60.00 $,"$10,756.93 CR",60.00 $,NaN,23 Jul,Value Date: 22/07/2022
26,23 Jul,LIBERTY JACKSONS RD NOBLE PARK NO VI AUS,NaN,NaN,NaN,NaN,23 Jul,LIBERTY JACKSONS RD NOBLE PARK NO VI AUS
27,NaN,Card xx5698,NaN,NaN,NaN,NaN,23 Jul,Card xx5698
28,NaN,Value Date: 21/07/2022,99.57 $,"$10,657.36 CR",99.57 $,NaN,23 Jul,Value Date: 21/07/2022
29,23 Jul,SURUR AFRICAN SUPER NOBLE PARK VI AUS,NaN,NaN,NaN,NaN,23 Jul,SURUR AFRICAN SUPER NOBLE PARK VI AUS
30,NaN,Card xx5698,NaN,NaN,NaN,NaN,23 Jul,Card xx5698
31,NaN,Value Date: 21/07/2022,56.00 $,"$10,601.36 CR",56.00 $,NaN,23 Jul,Value Date: 21/07/2022
32,25 Jul,Direct Debit 026160 RACV Assistance,NaN,NaN,NaN,NaN,25 Jul,Direct Debit 026160 RACV Assistance
33,NaN,RACV-0000-10441487,16.83 $,"$10,584.53 CR",16.83 $,NaN,25 Jul,RACV-0000-10441487
34,25 Jul,Direct Debit 026160 RACV Assistance,NaN,NaN,NaN,NaN,25 Jul,Direct Debit 026160 RACV Assistance
35,NaN,RACV-0000-10443085,18.89 $,"$10,565.64 CR",18.89 $,NaN,25 Jul,RACV-0000-10443085
36,25 Jul,Direct Credit 074806 BUPA_CREDIT-2507,NaN,NaN,NaN,NaN,25 Jul,Direct Credit 074806 BUPA_CREDIT-2507
37,NaN,B46484796 08033681,$100.60,"$10,666.24 CR",NaN,$100.60,25 Jul,B46484796 08033681
38,26 Jul,HENRYS MERCATO WAVER MULGRAVE AU,20.15 $,"$10,646.09 CR",20.15 $,NaN,26 Jul,HENRYS MERCATO WAVER MULGRAVE AU
39,26 Jul,ALDI STORES - WAVERLEY MULGRAVE AU,NaN,NaN,NaN,NaN,26 Jul,ALDI STORES - WAVERLEY MULGRAVE AU
40,NaN,Card xx6241,18.36 $,"$10,627.73 CR",18.36 $,NaN,26 Jul,Card xx6241
41,27 Jul,Salary MONASH UNIVERSIT,NaN,NaN,NaN,NaN,27 Jul,Salary MONASH UNIVERSIT
42,NaN,SALARY 01163158,"$1,226.56","$11,854.29 CR",NaN,"$1,226.56",27 Jul,SALARY 01163158
43,27 Jul,Salary Yooralla,NaN,NaN,NaN,NaN,27 Jul,Salary Yooralla
44,NaN,0009308,$171.77,"$12,026.06 CR",NaN,$171.77,27 Jul,0009308
45,27 Jul,Direct Credit 621009 SmartSalary,NaN,NaN,NaN,NaN,27 Jul,Direct Credit 621009 SmartSalary
46,NaN,GroupedSS,$508.32,"$12,534.38 CR",NaN,$508.32,27 Jul,GroupedSS
47,27 Jul,Salary HammondCare,NaN,NaN,NaN,NaN,27 Jul,Salary HammondCare
48,NaN,20052,$492.70,"$13,027.08 CR",NaN,$492.70,27 Jul,20052
49,28 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN,28 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU
50,NaN,Card xx6241,NaN,NaN,NaN,NaN,28 Jul,Card xx6241

In [ ]:
df_all4copy_renamed.Balance = df_all4copy_renamed.Balance.bfill()
df_all4copy_renamed.head(20)

,Date,Transaction Details,Debit Credit,Balance,Debit,Credit,New_Date,Details
1,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,"$10,467.01 CR",NaN,NaN,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS
2,NaN,Card xx6241,NaN,"$10,467.01 CR",NaN,NaN,19 Jul,Card xx6241
3,NaN,Value Date: 15/07/2022,11.05 $,"$10,467.01 CR",11.05 $,NaN,19 Jul,Value Date: 15/07/2022
4,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,"$10,455.96 CR",NaN,NaN,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS
5,NaN,Card xx6241,NaN,"$10,455.96 CR",NaN,NaN,20 Jul,Card xx6241
6,NaN,Value Date: 18/07/2022,11.05 $,"$10,455.96 CR",11.05 $,NaN,20 Jul,Value Date: 18/07/2022
7,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,"$10,436.87 CR",NaN,NaN,20 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS
8,NaN,Card xx6241,NaN,"$10,436.87 CR",NaN,NaN,20 Jul,Card xx6241
9,NaN,Value Date: 18/07/2022,19.09 $,"$10,436.87 CR",19.09 $,NaN,20 Jul,Value Date: 18/07/2022
10,20 Jul,HENRYS MERCATO WAVER MULGRAVE AU,8.37 $,"$10,428.50 CR",8.37 $,NaN,20 Jul,HENRYS MERCATO WAVER MULGRAVE AU
11,20 Jul,Direct Debit 518073 Performance Educ,NaN,"$9,527.18 CR",NaN,NaN,20 Jul,Direct Debit 518073 Performance Educ
12,NaN,EZYPAYID 323911303,901.32 $,"$9,527.18 CR",901.32 $,NaN,20 Jul,EZYPAYID 323911303
13,21 Jul,Salary Nextt Health PL,NaN,"$10,603.43 CR",NaN,NaN,21 Jul,Salary Nextt Health PL
14,NaN,10207717/07/2022,"$1,076.25","$10,603.43 CR",NaN,"$1,076.25",21 Jul,10207717/07/2022
15,22 Jul,COLES 0553 MULGRAVE AU AUS,NaN,"$10,594.43 CR",NaN,NaN,22 Jul,COLES 0553 MULGRAVE AU AUS
16,NaN,Card xx6241,NaN,"$10,594.43 CR",NaN,NaN,22 Jul,Card xx6241
17,NaN,Value Date: 20/07/2022,9.00 $,"$10,594.43 CR",9.00 $,NaN,22 Jul,Value Date: 20/07/2022
18,22 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,"$10,582.43 CR",NaN,NaN,22 Jul,WOOLWORTHS 3130 WAVERLEY GDNS AU AU
19,NaN,Card xx6241,NaN,"$10,582.43 CR",NaN,NaN,22 Jul,Card xx6241
20,NaN,Value Date: 20/07/2022,12.00 $,"$10,582.43 CR",12.00 $,NaN,22 Jul,Value Date: 20/07/2022

In [ ]:
# df_all4copy_renamed.Debit = df_all4copy_renamed.Debit.fillna(0)
# df_all4copy_renamed.Credit = df_all4copy_renamed.Credit.fillna(0)
# df_all4copy_renamed.head(20)

In [ ]:
# df_all4copy_renamed['New_Date_merge'][~(df_all4copy_renamed['New_Date_merge'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)] = np.nan

In [ ]:
df_all4copy_renamed.to_csv('output.csv', index=False)

Splitting the dataframe to extract 'New_Date','Details','Balance

In [ ]:
new_df = df_all4copy_renamed[['New_Date','Details','Balance']]

In [ ]:
#trying to append appropriate dates to the details of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_New_Df_2022 = new_df[new_df['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_New_Df_2022['New_Date'] = filtered_New_Df_2022['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_New_Df_2023 = new_df[new_df['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_New_Df_2023['New_Date'] = filtered_New_Df_2023['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenated_df = pd.concat([filtered_New_Df_2022, filtered_New_Df_2023])

concatenated_df

<ipython-input-111-c2cc93ac65ba>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_New_Df_2022['New_Date'] = filtered_New_Df_2022['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-111-c2cc93ac65ba>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_New_Df_2023['New_Date'] = filtered_New_Df_2023['New_Date'] + ' ' + year_to_concat_2023

         New_Date                               Details        Balance
1     19 Jul 2022    MON HLTH CLAY CPARK CLAYTON VI AUS  $10,467.01 CR
2     19 Jul 2022                           Card xx6241  $10,467.01 CR
3     19 Jul 2022                Value Date: 15/07/2022  $10,467.01 CR
4     20 Jul 2022    MON HLTH CLAY CPARK CLAYTON VI AUS  $10,455.96 CR
5     20 Jul 2022                           Card xx6241  $10,455.96 CR
...           ...                                   ...            ...
1485  30 Jun 2023       WOOLWORTHS 3130 MULGRAVE AU AUS   $4,257.88 CR
1486  30 Jun 2023                           Card xx6241   $4,257.88 CR
1487  30 Jun 2023                Value Date: 28/06/2023   $4,257.88 CR
1488  30 Jun 2023  Direct Debit 348045 AGL SALES PTY LT   $4,148.76 CR
1489  30 Jun 2023                          520010979544   $4,148.76 CR

[1448 rows x 3 columns]

In [ ]:
concatenated_df

         New_Date                               Details        Balance
1     19 Jul 2022    MON HLTH CLAY CPARK CLAYTON VI AUS  $10,467.01 CR
2     19 Jul 2022                           Card xx6241  $10,467.01 CR
3     19 Jul 2022                Value Date: 15/07/2022  $10,467.01 CR
4     20 Jul 2022    MON HLTH CLAY CPARK CLAYTON VI AUS  $10,455.96 CR
5     20 Jul 2022                           Card xx6241  $10,455.96 CR
...           ...                                   ...            ...
1485  30 Jun 2023       WOOLWORTHS 3130 MULGRAVE AU AUS   $4,257.88 CR
1486  30 Jun 2023                           Card xx6241   $4,257.88 CR
1487  30 Jun 2023                Value Date: 28/06/2023   $4,257.88 CR
1488  30 Jun 2023  Direct Debit 348045 AGL SALES PTY LT   $4,148.76 CR
1489  30 Jun 2023                          520010979544   $4,148.76 CR

[1448 rows x 3 columns]

In [ ]:
#Grouping the dataframe by 'New_Date','Balance' as they are unique for each transaction
merged_df_Details = concatenated_df.groupby(['New_Date','Balance'])['Details'].agg(lambda x: ','.join(map(str, x))).reset_index()

In [ ]:
merged_df_Details

,New_Date,Balance,Details
0,01 Apr 2023,"$2,908.52 CR",HENRYS MERCATO WAVER MULGRAVE AU
1,01 Aug 2022,"$14,778.31 CR","Direct Debit 314011 AGL TELCO,PAYWAY3264677184"
2,01 Dec 2022,"$5,685.75 CR","Transfer To Driving School,CommBank App from L..."
3,01 Dec 2022,"$5,724.49 CR","Transfer To Abraham Oladeji,CommBank App ayode..."
4,01 Dec 2022,"$5,740.75 CR","Salary Symmetry Human R,Symmetry HR W 1185"
...,...,...,...
677,31 May 2023,"$2,451.46 CR","Salary MONASH UNIVERSIT,SALARY 01163158"
678,31 May 2023,"$4,045.47 CR","Salary MONASH UNIVERSIT,SALARY 01163921"
679,31 May 2023,"$4,918.36 CR","Salary Yooralla,0009308"
680,31 May 2023,"$6,303.25 CR","Salary YNA,Payroll"
681,31 May 2023,"$6,543.59 CR","Direct Credit 621009 SmartSalary,GroupedSS"

In [ ]:
merged_df_Details[ merged_df_Details.Balance =='$4,148.76 CR']

,New_Date,Balance,Details
643,30 Jun 2023,"$4,148.76 CR","Direct Debit 348045 AGL SALES PTY LT,520010979544"

Splitting the dataframe to extract 'New_Date','Credit','Balance' to extract the Credit transaction

In [ ]:
new_df_credit = df_all4copy_renamed[['New_Date','Credit','Balance']]

In [ ]:
new_df_credit

     New_Date Credit        Balance
1      19 Jul    NaN  $10,467.01 CR
2      19 Jul    NaN  $10,467.01 CR
3      19 Jul    NaN  $10,467.01 CR
4      20 Jul    NaN  $10,455.96 CR
5      20 Jul    NaN  $10,455.96 CR
...       ...    ...            ...
1485   30 Jun    NaN   $4,257.88 CR
1486   30 Jun    NaN   $4,257.88 CR
1487   30 Jun    NaN   $4,257.88 CR
1488   30 Jun    NaN   $4,148.76 CR
1489   30 Jun    NaN   $4,148.76 CR

[1462 rows x 3 columns]

In [ ]:
#trying to append appropriate dates to the credit entry of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_New_Df_Credit_2022 = new_df_credit[new_df_credit['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_New_Df_Credit_2022['New_Date'] = filtered_New_Df_Credit_2022['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_New_Df_Credit_2023 = new_df_credit[new_df_credit['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_New_Df_Credit_2023['New_Date'] = filtered_New_Df_Credit_2023['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenated_Credit_df = pd.concat([filtered_New_Df_Credit_2022, filtered_New_Df_Credit_2023])

concatenated_Credit_df

<ipython-input-118-e63b9210a23e>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_New_Df_Credit_2022['New_Date'] = filtered_New_Df_Credit_2022['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-118-e63b9210a23e>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_New_Df_Credit_2023['New_Date'] = filtered_New_Df_Credit_2023['New_Date'] + ' ' + year_to_concat_2023

         New_Date Credit        Balance
1     19 Jul 2022    NaN  $10,467.01 CR
2     19 Jul 2022    NaN  $10,467.01 CR
3     19 Jul 2022    NaN  $10,467.01 CR
4     20 Jul 2022    NaN  $10,455.96 CR
5     20 Jul 2022    NaN  $10,455.96 CR
...           ...    ...            ...
1485  30 Jun 2023    NaN   $4,257.88 CR
1486  30 Jun 2023    NaN   $4,257.88 CR
1487  30 Jun 2023    NaN   $4,257.88 CR
1488  30 Jun 2023    NaN   $4,148.76 CR
1489  30 Jun 2023    NaN   $4,148.76 CR

[1448 rows x 3 columns]

In [ ]:
#filtering the nans in the credit transactions dataframe
filtered_credit = concatenated_Credit_df[~concatenated_Credit_df['Credit'].isnull()]
filtered_credit

         New_Date     Credit        Balance
14    21 Jul 2022  $1,076.25  $10,603.43 CR
22    22 Jul 2022    $234.50  $10,816.93 CR
37    25 Jul 2022    $100.60  $10,666.24 CR
42    27 Jul 2022  $1,226.56  $11,854.29 CR
44    27 Jul 2022    $171.77  $12,026.06 CR
...           ...        ...            ...
1448  21 Jun 2023    $800.77   $3,930.88 CR
1460  25 Jun 2023    $500.00   $4,257.88 CR
1478  28 Jun 2023  $2,369.88   $6,411.28 CR
1480  28 Jun 2023    $969.83   $7,381.11 CR
1482  28 Jun 2023    $941.16   $8,322.27 CR

[166 rows x 3 columns]

In [ ]:
#merger the credit data that had been filted for the values only with the
merged_df_Credit= merged_df_Details.merge(filtered_credit, on=['New_Date', 'Balance'], how='inner')
merged_df_Credit

,New_Date,Balance,Details,Credit
0,01 Dec 2022,"$5,740.75 CR","Salary Symmetry Human R,Symmetry HR W 1185",$16.26
1,01 Feb 2023,"$2,516.67 CR","Salary Symmetry Human R,Symmetry HR W 1239",$382.57
2,01 Feb 2023,"$3,663.11 CR","Salary Symmetry Human R,Symmetry HR W 1239","$1,146.44"
3,01 Mar 2023,"$4,939.97 CR","Salary Symmetry Human R,Symmetry HR W 1256","$1,401.64"
4,01 Mar 2023,"$5,299.68 CR","Salary Symmetry Human R,Symmetry HR W 1256",$359.71
...,...,...,...,...
161,31 May 2023,"$2,451.46 CR","Salary MONASH UNIVERSIT,SALARY 01163158","$1,264.89"
162,31 May 2023,"$4,045.47 CR","Salary MONASH UNIVERSIT,SALARY 01163921","$1,594.01"
163,31 May 2023,"$4,918.36 CR","Salary Yooralla,0009308",$872.89
164,31 May 2023,"$6,303.25 CR","Salary YNA,Payroll","$1,384.89"
165,31 May 2023,"$6,543.59 CR","Direct Credit 621009 SmartSalary,GroupedSS",$240.34

Doing similar steps for Debit transactions

In [ ]:
new_df_Debit = df_all4copy_renamed[['New_Date','Debit','Balance']]

In [ ]:
new_df_Debit

     New_Date     Debit        Balance
1      19 Jul       NaN  $10,467.01 CR
2      19 Jul       NaN  $10,467.01 CR
3      19 Jul   11.05 $  $10,467.01 CR
4      20 Jul       NaN  $10,455.96 CR
5      20 Jul       NaN  $10,455.96 CR
...       ...       ...            ...
1485   30 Jun       NaN   $4,257.88 CR
1486   30 Jun       NaN   $4,257.88 CR
1487   30 Jun   54.39 (   $4,257.88 CR
1488   30 Jun       NaN   $4,148.76 CR
1489   30 Jun  109.12 (   $4,148.76 CR

[1462 rows x 3 columns]

In [ ]:
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_New_Df_Debit_2022 = new_df_Debit[new_df_Debit['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_New_Df_Debit_2022['New_Date'] = filtered_New_Df_Debit_2022['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_New_Df_Debit_2023 = new_df_Debit[new_df_Debit['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_New_Df_Debit_2023['New_Date'] = filtered_New_Df_Debit_2023['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenated_Debit_df = pd.concat([filtered_New_Df_Debit_2022, filtered_New_Df_Debit_2023])

concatenated_Debit_df

<ipython-input-123-1a0d6e25776c>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_New_Df_Debit_2022['New_Date'] = filtered_New_Df_Debit_2022['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-123-1a0d6e25776c>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_New_Df_Debit_2023['New_Date'] = filtered_New_Df_Debit_2023['New_Date'] + ' ' + year_to_concat_2023

         New_Date     Debit        Balance
1     19 Jul 2022       NaN  $10,467.01 CR
2     19 Jul 2022       NaN  $10,467.01 CR
3     19 Jul 2022   11.05 $  $10,467.01 CR
4     20 Jul 2022       NaN  $10,455.96 CR
5     20 Jul 2022       NaN  $10,455.96 CR
...           ...       ...            ...
1485  30 Jun 2023       NaN   $4,257.88 CR
1486  30 Jun 2023       NaN   $4,257.88 CR
1487  30 Jun 2023   54.39 (   $4,257.88 CR
1488  30 Jun 2023       NaN   $4,148.76 CR
1489  30 Jun 2023  109.12 (   $4,148.76 CR

[1448 rows x 3 columns]

In [ ]:
filtered_Debit = concatenated_Debit_df[~concatenated_Debit_df['Debit'].isnull()]
filtered_Debit

         New_Date       Debit        Balance
3     19 Jul 2022     11.05 $  $10,467.01 CR
6     20 Jul 2022     11.05 $  $10,455.96 CR
9     20 Jul 2022     19.09 $  $10,436.87 CR
10    20 Jul 2022      8.37 $  $10,428.50 CR
12    20 Jul 2022    901.32 $   $9,527.18 CR
...           ...         ...            ...
1476  28 Jun 2023     20.14 (   $4,041.40 CR
1483  29 Jun 2023  4,000.00 (   $4,322.27 CR
1484  29 Jun 2023     10.00 (   $4,312.27 CR
1487  30 Jun 2023     54.39 (   $4,257.88 CR
1489  30 Jun 2023    109.12 (   $4,148.76 CR

[505 rows x 3 columns]

In [ ]:
#merging the credit data that had been filtered for the values only with the
merged_df_Debit = merged_df_Details.merge(filtered_Debit, on=['New_Date', 'Balance'], how='inner')
merged_df_Debit

,New_Date,Balance,Details,Debit
0,01 Apr 2023,"$2,908.52 CR",HENRYS MERCATO WAVER MULGRAVE AU,35.74 $
1,01 Aug 2022,"$14,778.31 CR","Direct Debit 314011 AGL TELCO,PAYWAY3264677184",68.00 $
2,01 Dec 2022,"$5,685.75 CR","Transfer To Driving School,CommBank App from L...",55.00 $
3,01 Dec 2022,"$5,724.49 CR","Transfer To Abraham Oladeji,CommBank App ayode...",500.00 $
4,01 Dec 2022,"$6,224.49 CR","Transfer To Driving School,CommBank App from L...",65.00 $
...,...,...,...,...
500,31 Mar 2023,"$3,048.66 CR","JB HI FI HOME CHADSTONE VI AUS,Card xx5698,Val...",47.50 $
501,31 Mar 2023,"$3,096.16 CR",Transfer to xx7964 CommBank app,"1,000.00 $"
502,31 May 2023,"$1,186.57 CR","SUSHI HUB WAVERLY GA MULGRAVE VI AUS,Card xx62...",18.00 (
503,31 May 2023,"$1,204.57 CR","International Transaction Fee,Value Date: 28/0...",2.96 (
504,31 May 2023,"$1,306.19 CR","International Transaction Fee,Value Date: 28/0...",95.22 (

In [ ]:
merged_df_all4 = pd.concat([ merged_df_Debit , merged_df_Credit], ignore_index=True)

In [ ]:
merged_df_all4.to_csv("Statement1.csv")

In [ ]:
merged_df_all4['New_Date'] = pd.to_datetime(merged_df_all4['New_Date'], format='%d %b %Y')

In [ ]:
merged_df_all4['New_Date'] = merged_df_all4['New_Date'].dt.strftime('%d-%b-%Y')

In [ ]:
merged_df_all4

,New_Date,Balance,Details,Debit,Credit
0,01-Apr-2023,"$2,908.52 CR",HENRYS MERCATO WAVER MULGRAVE AU,35.74 $,NaN
1,01-Aug-2022,"$14,778.31 CR","Direct Debit 314011 AGL TELCO,PAYWAY3264677184",68.00 $,NaN
2,01-Dec-2022,"$5,685.75 CR","Transfer To Driving School,CommBank App from L...",55.00 $,NaN
3,01-Dec-2022,"$5,724.49 CR","Transfer To Abraham Oladeji,CommBank App ayode...",500.00 $,NaN
4,01-Dec-2022,"$6,224.49 CR","Transfer To Driving School,CommBank App from L...",65.00 $,NaN
...,...,...,...,...,...
666,31-May-2023,"$2,451.46 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,264.89"
667,31-May-2023,"$4,045.47 CR","Salary MONASH UNIVERSIT,SALARY 01163921",NaN,"$1,594.01"
668,31-May-2023,"$4,918.36 CR","Salary Yooralla,0009308",NaN,$872.89
669,31-May-2023,"$6,303.25 CR","Salary YNA,Payroll",NaN,"$1,384.89"
670,31-May-2023,"$6,543.59 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$240.34

In [ ]:
df_sorted = merged_df_all4.sort_values('New_Date')

In [ ]:
df_sorted.head(50)

,New_Date,Balance,Details,Debit,Credit
270,2022-07-19,"$10,467.01 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05 $,NaN
291,2022-07-20,"$9,527.18 CR","Direct Debit 518073 Performance Educ,EZYPAYID ...",901.32 $,NaN
290,2022-07-20,"$10,455.96 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05 $,NaN
289,2022-07-20,"$10,436.87 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",19.09 $,NaN
288,2022-07-20,"$10,428.50 CR",HENRYS MERCATO WAVER MULGRAVE AU,8.37 $,NaN
610,2022-07-21,"$10,603.43 CR","Salary Nextt Health PL,10207717/07/2022",NaN,"$1,076.25"
329,2022-07-22,"$10,582.43 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",12.00 $,NaN
330,2022-07-22,"$10,594.43 CR","COLES 0553 MULGRAVE AU AUS,Card xx6241,Value D...",9.00 $,NaN
622,2022-07-22,"$10,816.93 CR","Direct Credit 141000 ELEVATE SUPPORT,PAY CHEQUE",NaN,$234.50
346,2022-07-23,"$10,601.36 CR","SURUR AFRICAN SUPER NOBLE PARK VI AUS,Card xx5...",56.00 $,NaN
347,2022-07-23,"$10,657.36 CR","LIBERTY JACKSONS RD NOBLE PARK NO VI AUS,Card ...",99.57 $,NaN
348,2022-07-23,"$10,756.93 CR","COSTCO FUEL MOORABBIN MOORABBIN AIR AUS,Card x...",60.00 $,NaN
641,2022-07-25,"$10,666.24 CR","Direct Credit 074806 BUPA_CREDIT-2507,B4648479...",NaN,$100.60
394,2022-07-25,"$10,584.53 CR","Direct Debit 026160 RACV Assistance,RACV-0000-...",16.83 $,NaN
393,2022-07-25,"$10,565.64 CR","Direct Debit 026160 RACV Assistance,RACV-0000-...",18.89 $,NaN
409,2022-07-26,"$10,627.73 CR","ALDI STORES - WAVERLEY MULGRAVE AU,Card xx6241",18.36 $,NaN
410,2022-07-26,"$10,646.09 CR",HENRYS MERCATO WAVER MULGRAVE AU,20.15 $,NaN
647,2022-07-27,"$12,534.38 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$508.32
645,2022-07-27,"$11,854.29 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,226.56"
648,2022-07-27,"$13,027.08 CR","Salary HammondCare,20052",NaN,$492.70
646,2022-07-27,"$12,026.06 CR","Salary Yooralla,0009308",NaN,$171.77
448,2022-07-28,"$12,977.18 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",49.90 $,NaN
652,2022-07-28,"$13,734.31 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$757.13
657,2022-07-29,"$15,280.65 CR","Salary 9D Care,9D Care",NaN,"$1,546.34"
477,2022-07-30,"$14,846.31 CR",UNITED CLAYTON CLAYTON AU,71.34 $,NaN
1,2022-08-01,"$14,778.31 CR","Direct Debit 314011 AGL TELCO,PAYWAY3264677184",68.00 $,NaN
22,2022-08-02,"$14,582.27 CR","ALLIANZ INSURE C6 SYDNEY NS AUS,Card xx5698,Va...",91.59 $,NaN
21,2022-08-02,"$14,569.77 CR","WOOLWORTHS 3940 CRANBOURNE W AU AUS,Card xx624...",12.50 $,NaN
23,2022-08-02,"$14,673.86 CR","NovaPharmacy Waverley Mulgrave VI AUS,Card xx5...",104.45 $,NaN
517,2022-08-04,"$15,324.24 CR","Salary Nextt Health PL,10207731/07/2022",NaN,$926.87
53,2022-08-04,"$14,499.77 CR","SKVORTSOV, ALEKSEI AL Noble Park No VI A,Card ...",70.00 $,NaN
52,2022-08-04,"$14,397.37 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",102.40 $,NaN
71,2022-08-06,"$15,305.15 CR","MOORABBIN CAR PARKING Bentleigh Eas AUS,Card x...",19.09 $,NaN
87,2022-08-07,"$10,305.15 CR","Transfer to xx7964 CommBank app,saving August","5,000.00 $",NaN
107,2022-08-09,"$10,289.45 CR","WOOLWORTHS 3940 CRANBOURNE W AU AUS,Card xx624...",15.70 $,NaN
108,2022-08-09,"$9,960.70 CR","PIERRE COLLET MOTORS BURWOOD AU,Card xx5698",328.75 $,NaN
121,2022-08-10,"$11,725.71 CR","Direct Debit 518073 Ezypay Pty Ltd C,EZYPAYID ...",0.55 $,NaN
122,2022-08-10,"$9,896.04 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx...",64.66 $,NaN
552,2022-08-10,"$11,726.26 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,226.56"
551,2022-08-10,"$10,499.70 CR","Salary MONASH UNIVERSIT,SALARY 01163921",NaN,$603.66
553,2022-08-10,"$12,178.71 CR","Salary HammondCare,20052",NaN,$453.00
556,2022-08-11,"$12,867.43 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$757.13
557,2022-08-11,"$14,370.07 CR","Salary 9D Care,9D Care",NaN,"$1,502.64"
136,2022-08-11,"$12,110.30 CR","COLES 0584 BURWOOD EAST AU AUS,Card xx6241,Val...",48.20 $,NaN
137,2022-08-11,"$12,158.50 CR","BETTER CHOICE BURWOOD BURWOOD AUS,Card xx6241,...",20.21 $,NaN
163,2022-08-13,"$14,269.07 CR","SURUR AFRICAN SUPER NOBLE PARK VI AUS,Card xx5...",101.00 $,NaN
186,2022-08-15,"$11,679.52 CR","Direct Debit 507533 SOUTH EAST WATER,DT.wqlxr ...",62.00 $,NaN
188,2022-08-15,"$12,967.84 CR","ALDI STORES - WAVERLEY MULGRAVE AU,Card xx6241",17.23 $,NaN
187,2022-08-15,"$11,741.52 CR","Direct Debit 518073 Performance Educ,EZYPAYID ...","1,226.32 $",NaN
210,2022-08-16,"$11,598.87 CR","AA MULGRAVE 3222 MULGRAVE VI AUS,Card xx5698,V...",80.65 $,NaN

df_all6_1_1

In [ ]:
df_all6_1_1.tail(51)

,Date,Transaction,Debit,Unnamed: 0,Credit,Balance
59,19 Jul,WPNP PTY LTD NetBank BPAY 304303,NaN,NaN,NaN,NaN
60,NaN,1635571282 rent,"1,651.00",$,NaN,"$10,559.37 CR"
61,19 Jul,COLES EXPRESS 6805 NOBLE PARK N AU AUS,NaN,NaN,NaN,NaN
62,NaN,Card xx6241,NaN,NaN,NaN,NaN
63,NaN,Value Date: 17/07/2022,70.26,$,NaN,"$10,489.11 CR"
64,19 Jul,MON HLTH CLAY CPARK CLAYTON VI AUS,NaN,NaN,NaN,NaN
65,NaN,Card xx6241,NaN,NaN,NaN,NaN
66,NaN,Value Date: 15/07/2022,11.05,$,NaN,"$10,478.06 CR"
67,11 Jan,Salary Symmetry Human R,NaN,NaN,NaN,NaN
68,NaN,Symmetry HR W 1221,NaN,NaN,$893.76,"$8,067.59 CR"
69,11 Jan,Direct Credit 621009 SmartSalary,NaN,NaN,NaN,NaN
70,NaN,GroupedSS,NaN,NaN,"$2,778.82","$10,846.41 CR"
71,11 Jan,Transfer to xx7964 CommBank app,"5,000.00",$,NaN,"$5,846.41 CR"
72,12 Jan,Transfer To Regeneration Church,NaN,NaN,NaN,NaN
73,NaN,CommBank App 6 forthnigths,600.00,$,NaN,"$5,246.41 CR"
74,14 Jan,AA OFFCR OTBND7020 OFFICER SOUTH VI AUS,NaN,NaN,NaN,NaN
75,NaN,Card xx5698,NaN,NaN,NaN,NaN
76,NaN,Value Date: 11/01/2023,56.05,$,NaN,"$5,190.36 CR"
77,15 Jan,T*M Tickets-CSS - Sat,35.00,$,NaN,"$5,155.36 CR"
78,16 Jan,PAT'S MUSIC OAKLEIGH SOUTVICAU,42.28,$,NaN,"$5,113.08 CR"
79,16 Jan,HENRYS MERCATO WAVER MULGRAVE AU,50.22,$,NaN,"$5,062.86 CR"
80,16 Jan,Direct Debit 507533 SOUTH EAST WATER,NaN,NaN,NaN,NaN
81,NaN,DT.1bqjog 76645649,62.00,$,NaN,"$5,000.86 CR"
82,17 Jan,ANDRE J MENSWEAR CLAYTON VICAU,350.00,$,NaN,"$4,650.86 CR"
83,18 Jan,Direct Debit 000793 BUPA AUSTRALIA,NaN,NaN,NaN,NaN
84,NaN,464847960000010000,602.38,$,NaN,"$4,048.48 CR"
85,18 Jan,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN
86,NaN,Card xx6241,NaN,NaN,NaN,NaN
87,NaN,Value Date: 16/01/2023,42.50,$,NaN,"$4,005.98 CR"
88,18 Jan,Salary Symmetry Human R,NaN,NaN,NaN,NaN
89,NaN,Symmetry HR W 1227,NaN,NaN,"$1,370.10","$5,376.08 CR"
90,18 Jan,Salary Symmetry Human R,NaN,NaN,NaN,NaN
91,NaN,Symmetry HR W 1227,NaN,NaN,$382.57,"$5,758.65 CR"
92,19 Jan,Direct Debit 157640 RACV INSURANCE,NaN,NaN,NaN,NaN
93,NaN,MOT739495963230119,52.43,$,NaN,"$5,706.22 CR"
94,19 Jan,Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,NaN
95,NaN,HACSU Membership,28.00,$,NaN,"$5,678.22 CR"
96,19 Jan,Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,NaN
97,NaN,HACSU Membership,28.00,$,NaN,"$5,650.22 CR"
98,21 Jan,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN
99,NaN,Card xx6241,NaN,NaN,NaN,NaN
100,NaN,Value Date: 19/01/2023,42.30,$,NaN,"$5,607.92 CR"
101,22 Jan,Transfer to xx7964 CommBank app,"2,000.00",$,NaN,"$3,607.92 CR"
102,22 Jan,Fast Transfer From RENTPAY TECHNOLOGY PT,NaN,NaN,NaN,NaN
103,NaN,Account Verification,NaN,NaN,NaN,NaN
104,NaN,Account Verification,NaN,NaN,$0.10,"$3,608.02 CR"
105,22 Jan,WPNP PTY LTD CommBank app BPAY 3,NaN,NaN,NaN,NaN
106,NaN,1635571282 rent,"1,651.00",$,NaN,"$1,957.02 CR"
107,24 Jan,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN,NaN
108,NaN,Card xx5698,NaN,NaN,NaN,NaN
109,NaN,Value Date: 22/01/2023,32.70,$,NaN,"$1,924.32 CR"

In [ ]:
df_all6_1_1 = df_all6_1_1.drop(['Unnamed: 0'], axis=1)

In [ ]:
df_all6_1_1

,Date,Transaction,Debit,Credit,Balance
0,01 Jul,2022 OPENING BALANCE,NaN,NaN,"$6,622.66 CR"
1,01 Jul,Salary 9D Care,NaN,NaN,NaN
2,NaN,9D Care,NaN,$275.22,"$6,897.88 CR"
3,04 Jul,Direct Credit 074806 BUPA_CLM_CR-0407,NaN,NaN,NaN
4,NaN,C57037079 07876718,NaN,$100.60,"$6,998.48 CR"
...,...,...,...,...,...
105,22 Jan,WPNP PTY LTD CommBank app BPAY 3,NaN,NaN,NaN
106,NaN,1635571282 rent,"1,651.00",NaN,"$1,957.02 CR"
107,24 Jan,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN
108,NaN,Card xx5698,NaN,NaN,NaN
109,NaN,Value Date: 22/01/2023,32.70,NaN,"$1,924.32 CR"

In [ ]:
df_all6_1_1.Date = df_all6_1_1.Date.ffill()

In [ ]:
df_all6_1_1

,Date,Transaction,Debit,Credit,Balance
0,01 Jul,2022 OPENING BALANCE,NaN,NaN,"$6,622.66 CR"
1,01 Jul,Salary 9D Care,NaN,NaN,NaN
2,01 Jul,9D Care,NaN,$275.22,"$6,897.88 CR"
3,04 Jul,Direct Credit 074806 BUPA_CLM_CR-0407,NaN,NaN,NaN
4,04 Jul,C57037079 07876718,NaN,$100.60,"$6,998.48 CR"
...,...,...,...,...,...
105,22 Jan,WPNP PTY LTD CommBank app BPAY 3,NaN,NaN,NaN
106,22 Jan,1635571282 rent,"1,651.00",NaN,"$1,957.02 CR"
107,24 Jan,WOOLWORTHS 3130 WAVERLEY GDNS AU AU,NaN,NaN,NaN
108,24 Jan,Card xx5698,NaN,NaN,NaN
109,24 Jan,Value Date: 22/01/2023,32.70,NaN,"$1,924.32 CR"

In [ ]:
df_all6_1_1.Balance = df_all6_1_1.Balance.bfill()

In [ ]:
df_all6_1_1 = df_all6_1_1.rename(columns={"Date": "New_Date", "Transaction": "Details"})

In [ ]:
new_df_all6_1_1 = df_all6_1_1[['New_Date','Details','Balance']]

In [ ]:
new_df_all6_1_1

    New_Date                                Details       Balance
0     01 Jul                   2022 OPENING BALANCE  $6,622.66 CR
1     01 Jul                         Salary 9D Care  $6,897.88 CR
2     01 Jul                                9D Care  $6,897.88 CR
3     04 Jul  Direct Credit 074806 BUPA_CLM_CR-0407  $6,998.48 CR
4     04 Jul                     C57037079 07876718  $6,998.48 CR
..       ...                                    ...           ...
105   22 Jan       WPNP PTY LTD CommBank app BPAY 3  $1,957.02 CR
106   22 Jan                        1635571282 rent  $1,957.02 CR
107   24 Jan    WOOLWORTHS 3130 WAVERLEY GDNS AU AU  $1,924.32 CR
108   24 Jan                            Card xx5698  $1,924.32 CR
109   24 Jan                 Value Date: 22/01/2023  $1,924.32 CR

[110 rows x 3 columns]

In [ ]:
#trying to append appropriate dates to the details of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_new_df_all6_1_1_2022 = new_df_all6_1_1[new_df_all6_1_1['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_1_2022['New_Date'] = filtered_new_df_all6_1_1_2022['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_new_df_all6_1_1_2023 = new_df_all6_1_1[new_df_all6_1_1['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_1_2023['New_Date'] = filtered_new_df_all6_1_1_2023['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenatednew_df_all6_1_1_df = pd.concat([filtered_new_df_all6_1_1_2022, filtered_new_df_all6_1_1_2023])

concatenatednew_df_all6_1_1_df

<ipython-input-171-166b9ba9f5f1>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_1_2022['New_Date'] = filtered_new_df_all6_1_1_2022['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-171-166b9ba9f5f1>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_1_2023['New_Date'] = filtered_new_df_all6_1_1_2023['New_Date'] + ' ' + year_to_concat_2023

        New_Date                                Details       Balance
0    01 Jul 2022                   2022 OPENING BALANCE  $6,622.66 CR
1    01 Jul 2022                         Salary 9D Care  $6,897.88 CR
2    01 Jul 2022                                9D Care  $6,897.88 CR
3    04 Jul 2022  Direct Credit 074806 BUPA_CLM_CR-0407  $6,998.48 CR
4    04 Jul 2022                     C57037079 07876718  $6,998.48 CR
..           ...                                    ...           ...
105  22 Jan 2023       WPNP PTY LTD CommBank app BPAY 3  $1,957.02 CR
106  22 Jan 2023                        1635571282 rent  $1,957.02 CR
107  24 Jan 2023    WOOLWORTHS 3130 WAVERLEY GDNS AU AU  $1,924.32 CR
108  24 Jan 2023                            Card xx5698  $1,924.32 CR
109  24 Jan 2023                 Value Date: 22/01/2023  $1,924.32 CR

[110 rows x 3 columns]

In [ ]:
#Grouping the dataframe by 'New_Date','Balance' as they are unique for each transaction
merged_df_all6_1_1_df_Details = concatenatednew_df_all6_1_1_df.groupby(['New_Date','Balance'])['Details'].agg(lambda x: ','.join(map(str, x))).reset_index()

In [ ]:
merged_df_all6_1_1_df_Details

,New_Date,Balance,Details
0,01 Jul 2022,"$6,622.66 CR",2022 OPENING BALANCE
1,01 Jul 2022,"$6,897.88 CR","Salary 9D Care,9D Care"
2,04 Jul 2022,"$6,998.48 CR","Direct Credit 074806 BUPA_CLM_CR-0407,C5703707..."
3,05 Jul 2022,"$6,780.80 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241"
4,05 Jul 2022,"$6,835.77 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241"
5,05 Jul 2022,"$6,862.76 CR","Return COSTCO WHOLESALE AUS MOORABBI,Card xx6241"
6,06 Jul 2022,"$11,780.80 CR","Transfer From A A LADEINDE,Part of Professiona..."
7,07 Jul 2022,"$11,780.50 CR","OFFICEWORKS 0348 KEYSBOROUGH AU AUS,Card xx624..."
8,07 Jul 2022,"$11,841.58 CR","Salary Nextt Health PL,1020773/07/2022"
9,11 Jan 2023,"$10,846.41 CR","Direct Credit 621009 SmartSalary,GroupedSS"
10,11 Jan 2023,"$5,846.41 CR",Transfer to xx7964 CommBank app
11,11 Jan 2023,"$8,067.59 CR","Salary Symmetry Human R,Symmetry HR W 1221"
12,12 Jan 2023,"$5,246.41 CR","Transfer To Regeneration Church,CommBank App 6..."
13,12 Jul 2022,"$11,647.06 CR","QANDI FRESH PTY LTD DANDENONG AU,Card xx6241"
14,12 Jul 2022,"$11,666.51 CR",PREMIER POULTRY DANDEN DANDENONG AU
15,12 Jul 2022,"$11,682.79 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241"
16,12 Jul 2022,"$11,700.56 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241"
17,12 Jul 2022,"$11,713.68 CR","WOOLWORTHS 3806 CLAYTON AU AUS,Card xx6241,Val..."
18,12 Jul 2022,"$11,745.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da..."
19,12 Jul 2022,"$11,763.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da..."
20,13 Jul 2022,"$12,873.62 CR","Salary MONASH UNIVERSIT,SALARY 01163158"
21,13 Jul 2022,"$13,411.16 CR","Salary Yooralla,0009308"
22,13 Jul 2022,"$15,014.10 CR","Direct Debit 066429 Linkt Melbourne,48131845-7..."
23,13 Jul 2022,"$15,016.78 CR","Direct Credit 621009 SmartSalary,GroupedSS"
24,13 Jul 2022,"$15,708.16 CR","Salary HammondCare,20052"
25,14 Jan 2023,"$5,190.36 CR","AA OFFCR OTBND7020 OFFICER SOUTH VI AUS,Card x..."
26,14 Jul 2022,"$11,465.29 CR","Transfer to xx7964 CommBank app,July sa"
27,14 Jul 2022,"$16,465.29 CR","Direct Credit 621009 SmartSalary,GroupedSS"
28,15 Jan 2023,"$5,155.36 CR",T*M Tickets-CSS - Sat
29,15 Jul 2022,"$11,392.41 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx..."
30,15 Jul 2022,"$11,443.19 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241..."
31,15 Jul 2022,"$11,454.24 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241..."
32,15 Jul 2022,"$12,210.37 CR","Salary 9D Care,9D Care"
33,16 Jan 2023,"$5,000.86 CR","Direct Debit 507533 SOUTH EAST WATER,DT.1bqjog..."
34,16 Jan 2023,"$5,062.86 CR",HENRYS MERCATO WAVER MULGRAVE AU
35,16 Jan 2023,"$5,113.08 CR",PAT'S MUSIC OAKLEIGH SOUTVICAU
36,17 Jan 2023,"$4,650.86 CR",ANDRE J MENSWEAR CLAYTON VICAU
37,18 Jan 2023,"$4,005.98 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624..."
38,18 Jan 2023,"$4,048.48 CR","Direct Debit 000793 BUPA AUSTRALIA,46484796000..."
39,18 Jan 2023,"$5,376.08 CR","Salary Symmetry Human R,Symmetry HR W 1227"
40,18 Jan 2023,"$5,758.65 CR","Salary Symmetry Human R,Symmetry HR W 1227"
41,19 Jan 2023,"$5,650.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership"
42,19 Jan 2023,"$5,678.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership"
43,19 Jan 2023,"$5,706.22 CR","Direct Debit 157640 RACV INSURANCE,MOT73949596..."
44,19 Jul 2022,"$10,478.06 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241..."
45,19 Jul 2022,"$10,489.11 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx..."
46,19 Jul 2022,"$10,559.37 CR","WPNP PTY LTD NetBank BPAY 304303,1635571282 rent"
47,21 Jan 2023,"$5,607.92 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624..."
48,22 Jan 2023,"$1,957.02 CR","WPNP PTY LTD CommBank app BPAY 3,1635571282 rent"
49,22 Jan 2023,"$3,607.92 CR",Transfer to xx7964 CommBank app
50,22 Jan 2023,"$3,608.02 CR","Fast Transfer From RENTPAY TECHNOLOGY PT,Accou..."
51,24 Jan 2023,"$1,924.32 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx569..."

In [ ]:
new_df_all6_1_1_Credit = df_all6_1_1[['New_Date','Balance','Credit']]
new_df_all6_1_1_Debit = df_all6_1_1[['New_Date','Balance','Debit']]

In [ ]:
new_df_all6_1_1_Credit

    New_Date       Balance   Credit
0     01 Jul  $6,622.66 CR      NaN
1     01 Jul  $6,897.88 CR      NaN
2     01 Jul  $6,897.88 CR  $275.22
3     04 Jul  $6,998.48 CR      NaN
4     04 Jul  $6,998.48 CR  $100.60
..       ...           ...      ...
105   22 Jan  $1,957.02 CR      NaN
106   22 Jan  $1,957.02 CR      NaN
107   24 Jan  $1,924.32 CR      NaN
108   24 Jan  $1,924.32 CR      NaN
109   24 Jan  $1,924.32 CR      NaN

[110 rows x 3 columns]

In [ ]:
#trying to append appropriate dates to the details of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_new_df_all6_1_1_2022_Credit = new_df_all6_1_1_Credit[new_df_all6_1_1_Credit['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_1_2022_Credit['New_Date'] = filtered_new_df_all6_1_1_2022_Credit['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_new_df_all6_1_1_2023_Credit = new_df_all6_1_1_Credit[new_df_all6_1_1_Credit['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_1_2023_Credit['New_Date'] = filtered_new_df_all6_1_1_2023_Credit['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenatednew_df_all6_1_1_df_Credit = pd.concat([filtered_new_df_all6_1_1_2022_Credit, filtered_new_df_all6_1_1_2023_Credit])

concatenatednew_df_all6_1_1_df_Credit

<ipython-input-177-b890fe9c4d6d>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_1_2022_Credit['New_Date'] = filtered_new_df_all6_1_1_2022_Credit['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-177-b890fe9c4d6d>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_1_2023_Credit['New_Date'] = filtered_new_df_all6_1_1_2023_Credit['New_Date'] + ' ' + year_to_concat_2023

        New_Date       Balance   Credit
0    01 Jul 2022  $6,622.66 CR      NaN
1    01 Jul 2022  $6,897.88 CR      NaN
2    01 Jul 2022  $6,897.88 CR  $275.22
3    04 Jul 2022  $6,998.48 CR      NaN
4    04 Jul 2022  $6,998.48 CR  $100.60
..           ...           ...      ...
105  22 Jan 2023  $1,957.02 CR      NaN
106  22 Jan 2023  $1,957.02 CR      NaN
107  24 Jan 2023  $1,924.32 CR      NaN
108  24 Jan 2023  $1,924.32 CR      NaN
109  24 Jan 2023  $1,924.32 CR      NaN

[110 rows x 3 columns]

In [ ]:
#filtering the nans in the credit transactions dataframe
filtered_concatenatednew_df_all6_1_1_df_Credit = concatenatednew_df_all6_1_1_df_Credit[~concatenatednew_df_all6_1_1_df_Credit['Credit'].isnull()]
filtered_concatenatednew_df_all6_1_1_df_Credit

        New_Date        Balance     Credit
2    01 Jul 2022   $6,897.88 CR    $275.22
4    04 Jul 2022   $6,998.48 CR    $100.60
8    05 Jul 2022   $6,862.76 CR     $26.99
12   06 Jul 2022  $11,780.80 CR  $5,000.00
17   07 Jul 2022  $11,841.58 CR     $61.08
35   13 Jul 2022  $12,873.62 CR  $1,226.56
37   13 Jul 2022  $13,411.16 CR    $537.54
39   13 Jul 2022  $15,016.78 CR  $1,605.62
43   13 Jul 2022  $15,708.16 CR    $694.06
45   14 Jul 2022  $16,465.29 CR    $757.13
58   15 Jul 2022  $12,210.37 CR    $817.96
68   11 Jan 2023   $8,067.59 CR    $893.76
70   11 Jan 2023  $10,846.41 CR  $2,778.82
89   18 Jan 2023   $5,376.08 CR  $1,370.10
91   18 Jan 2023   $5,758.65 CR    $382.57
104  22 Jan 2023   $3,608.02 CR      $0.10

In [ ]:
#merger the credit data that had been filted for the values only with the
merged_df_Credit_all6_1_1_df = merged_df_all6_1_1_df_Details.merge(filtered_concatenatednew_df_all6_1_1_df_Credit, on=['New_Date', 'Balance'], how='inner')
merged_df_Credit_all6_1_1_df

,New_Date,Balance,Details,Credit
0,01 Jul 2022,"$6,897.88 CR","Salary 9D Care,9D Care",$275.22
1,04 Jul 2022,"$6,998.48 CR","Direct Credit 074806 BUPA_CLM_CR-0407,C5703707...",$100.60
2,05 Jul 2022,"$6,862.76 CR","Return COSTCO WHOLESALE AUS MOORABBI,Card xx6241",$26.99
3,06 Jul 2022,"$11,780.80 CR","Transfer From A A LADEINDE,Part of Professiona...","$5,000.00"
4,07 Jul 2022,"$11,841.58 CR","Salary Nextt Health PL,1020773/07/2022",$61.08
5,11 Jan 2023,"$10,846.41 CR","Direct Credit 621009 SmartSalary,GroupedSS","$2,778.82"
6,11 Jan 2023,"$8,067.59 CR","Salary Symmetry Human R,Symmetry HR W 1221",$893.76
7,13 Jul 2022,"$12,873.62 CR","Salary MONASH UNIVERSIT,SALARY 01163158","$1,226.56"
8,13 Jul 2022,"$13,411.16 CR","Salary Yooralla,0009308",$537.54
9,13 Jul 2022,"$15,016.78 CR","Direct Credit 621009 SmartSalary,GroupedSS","$1,605.62"
10,13 Jul 2022,"$15,708.16 CR","Salary HammondCare,20052",$694.06
11,14 Jul 2022,"$16,465.29 CR","Direct Credit 621009 SmartSalary,GroupedSS",$757.13
12,15 Jul 2022,"$12,210.37 CR","Salary 9D Care,9D Care",$817.96
13,18 Jan 2023,"$5,376.08 CR","Salary Symmetry Human R,Symmetry HR W 1227","$1,370.10"
14,18 Jan 2023,"$5,758.65 CR","Salary Symmetry Human R,Symmetry HR W 1227",$382.57
15,22 Jan 2023,"$3,608.02 CR","Fast Transfer From RENTPAY TECHNOLOGY PT,Accou...",$0.10

In [ ]:
new_df_all6_1_1_Debit

    New_Date       Balance     Debit
0     01 Jul  $6,622.66 CR       NaN
1     01 Jul  $6,897.88 CR       NaN
2     01 Jul  $6,897.88 CR       NaN
3     04 Jul  $6,998.48 CR       NaN
4     04 Jul  $6,998.48 CR       NaN
..       ...           ...       ...
105   22 Jan  $1,957.02 CR       NaN
106   22 Jan  $1,957.02 CR  1,651.00
107   24 Jan  $1,924.32 CR       NaN
108   24 Jan  $1,924.32 CR       NaN
109   24 Jan  $1,924.32 CR     32.70

[110 rows x 3 columns]

In [ ]:
#trying to append appropriate dates to the details of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_new_df_all6_1_1_2022_Debit = new_df_all6_1_1_Debit[new_df_all6_1_1_Debit['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_1_2022_Debit['New_Date'] = filtered_new_df_all6_1_1_2022_Debit['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_new_df_all6_1_1_2023_Debit = new_df_all6_1_1_Debit[new_df_all6_1_1_Debit['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_1_2023_Debit['New_Date'] = filtered_new_df_all6_1_1_2023_Debit['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenatednew_df_all6_1_1_df_Debit = pd.concat([filtered_new_df_all6_1_1_2022_Debit, filtered_new_df_all6_1_1_2023_Debit])

concatenatednew_df_all6_1_1_df_Debit

<ipython-input-181-0fab7d072440>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_1_2022_Debit['New_Date'] = filtered_new_df_all6_1_1_2022_Debit['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-181-0fab7d072440>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_1_2023_Debit['New_Date'] = filtered_new_df_all6_1_1_2023_Debit['New_Date'] + ' ' + year_to_concat_2023

        New_Date       Balance     Debit
0    01 Jul 2022  $6,622.66 CR       NaN
1    01 Jul 2022  $6,897.88 CR       NaN
2    01 Jul 2022  $6,897.88 CR       NaN
3    04 Jul 2022  $6,998.48 CR       NaN
4    04 Jul 2022  $6,998.48 CR       NaN
..           ...           ...       ...
105  22 Jan 2023  $1,957.02 CR       NaN
106  22 Jan 2023  $1,957.02 CR  1,651.00
107  24 Jan 2023  $1,924.32 CR       NaN
108  24 Jan 2023  $1,924.32 CR       NaN
109  24 Jan 2023  $1,924.32 CR     32.70

[110 rows x 3 columns]

In [ ]:
#filtering the nans in the credit transactions dataframe
filtered_concatenatednew_df_all6_1_1_df_Debit = concatenatednew_df_all6_1_1_df_Debit[~concatenatednew_df_all6_1_1_df_Debit['Debit'].isnull()]
filtered_concatenatednew_df_all6_1_1_df_Debit

        New_Date        Balance     Debit
6    05 Jul 2022   $6,835.77 CR    162.71
10   05 Jul 2022   $6,780.80 CR     81.96
15   07 Jul 2022  $11,780.50 CR       0.3
20   12 Jul 2022  $11,763.58 CR      78.0
23   12 Jul 2022  $11,745.58 CR      18.0
26   12 Jul 2022  $11,713.68 CR     31.90
28   12 Jul 2022  $11,700.56 CR     13.12
30   12 Jul 2022  $11,682.79 CR     17.77
31   12 Jul 2022  $11,666.51 CR     16.28
33   12 Jul 2022  $11,647.06 CR     19.45
41   13 Jul 2022  $15,014.10 CR      2.68
47   14 Jul 2022  $11,465.29 CR  5,000.00
50   15 Jul 2022  $11,454.24 CR     11.05
53   15 Jul 2022  $11,443.19 CR     11.05
56   15 Jul 2022  $11,392.41 CR     50.78
60   19 Jul 2022  $10,559.37 CR  1,651.00
63   19 Jul 2022  $10,489.11 CR     70.26
66   19 Jul 2022  $10,478.06 CR     11.05
71   11 Jan 2023   $5,846.41 CR  5,000.00
73   12 Jan 2023   $5,246.41 CR    600.00
76   14 Jan 2023   $5,190.36 CR     56.05
77   15 Jan 2023   $5,155.36 CR     35.00
78   16 Jan 2023   $5,113.08 CR     42.28
79   16 Jan 2023   $5,062.86 CR     50.22
81   16 Jan 2023   $5,000.86 CR     62.00
82   17 Jan 2023   $4,650.86 CR    350.00
84   18 Jan 2023   $4,048.48 CR    602.38
87   18 Jan 2023   $4,005.98 CR     42.50
93   19 Jan 2023   $5,706.22 CR     52.43
95   19 Jan 2023   $5,678.22 CR     28.00
97   19 Jan 2023   $5,650.22 CR     28.00
100  21 Jan 2023   $5,607.92 CR     42.30
101  22 Jan 2023   $3,607.92 CR  2,000.00
106  22 Jan 2023   $1,957.02 CR  1,651.00
109  24 Jan 2023   $1,924.32 CR     32.70

In [ ]:
#merger the credit data that had been filted for the values only with the
merged_df_Debit_all6_1_1_df = merged_df_all6_1_1_df_Details.merge(filtered_concatenatednew_df_all6_1_1_df_Debit, on=['New_Date', 'Balance'], how='inner')
merged_df_Debit_all6_1_1_df

,New_Date,Balance,Details,Debit
0,05 Jul 2022,"$6,780.80 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241",81.96
1,05 Jul 2022,"$6,835.77 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241",162.71
2,07 Jul 2022,"$11,780.50 CR","OFFICEWORKS 0348 KEYSBOROUGH AU AUS,Card xx624...",0.3
3,11 Jan 2023,"$5,846.41 CR",Transfer to xx7964 CommBank app,"5,000.00"
4,12 Jan 2023,"$5,246.41 CR","Transfer To Regeneration Church,CommBank App 6...",600.00
5,12 Jul 2022,"$11,647.06 CR","QANDI FRESH PTY LTD DANDENONG AU,Card xx6241",19.45
6,12 Jul 2022,"$11,666.51 CR",PREMIER POULTRY DANDEN DANDENONG AU,16.28
7,12 Jul 2022,"$11,682.79 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241",17.77
8,12 Jul 2022,"$11,700.56 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241",13.12
9,12 Jul 2022,"$11,713.68 CR","WOOLWORTHS 3806 CLAYTON AU AUS,Card xx6241,Val...",31.90
10,12 Jul 2022,"$11,745.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da...",18.0
11,12 Jul 2022,"$11,763.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da...",78.0
12,13 Jul 2022,"$15,014.10 CR","Direct Debit 066429 Linkt Melbourne,48131845-7...",2.68
13,14 Jan 2023,"$5,190.36 CR","AA OFFCR OTBND7020 OFFICER SOUTH VI AUS,Card x...",56.05
14,14 Jul 2022,"$11,465.29 CR","Transfer to xx7964 CommBank app,July sa","5,000.00"
15,15 Jan 2023,"$5,155.36 CR",T*M Tickets-CSS - Sat,35.00
16,15 Jul 2022,"$11,392.41 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx...",50.78
17,15 Jul 2022,"$11,443.19 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05
18,15 Jul 2022,"$11,454.24 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05
19,16 Jan 2023,"$5,000.86 CR","Direct Debit 507533 SOUTH EAST WATER,DT.1bqjog...",62.00
20,16 Jan 2023,"$5,062.86 CR",HENRYS MERCATO WAVER MULGRAVE AU,50.22
21,16 Jan 2023,"$5,113.08 CR",PAT'S MUSIC OAKLEIGH SOUTVICAU,42.28
22,17 Jan 2023,"$4,650.86 CR",ANDRE J MENSWEAR CLAYTON VICAU,350.00
23,18 Jan 2023,"$4,005.98 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",42.50
24,18 Jan 2023,"$4,048.48 CR","Direct Debit 000793 BUPA AUSTRALIA,46484796000...",602.38
25,19 Jan 2023,"$5,650.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership",28.00
26,19 Jan 2023,"$5,678.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership",28.00
27,19 Jan 2023,"$5,706.22 CR","Direct Debit 157640 RACV INSURANCE,MOT73949596...",52.43
28,19 Jul 2022,"$10,478.06 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05
29,19 Jul 2022,"$10,489.11 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx...",70.26
30,19 Jul 2022,"$10,559.37 CR","WPNP PTY LTD NetBank BPAY 304303,1635571282 rent","1,651.00"
31,21 Jan 2023,"$5,607.92 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",42.30
32,22 Jan 2023,"$1,957.02 CR","WPNP PTY LTD CommBank app BPAY 3,1635571282 rent","1,651.00"
33,22 Jan 2023,"$3,607.92 CR",Transfer to xx7964 CommBank app,"2,000.00"
34,24 Jan 2023,"$1,924.32 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx569...",32.70

In [ ]:
merged_df_all6_1_1 = pd.concat([ merged_df_Debit_all6_1_1_df , merged_df_Credit_all6_1_1_df], ignore_index=True)

In [ ]:
merged_df_all6_1_1['New_Date'] = pd.to_datetime(merged_df_all6_1_1['New_Date'], format='%d %b %Y')

In [ ]:
merged_df_all6_1_1['New_Date'] = merged_df_all6_1_1['New_Date'].dt.strftime('%d-%b-%Y')

In [ ]:
merged_df_all6_1_1.to_csv("Statement2.csv")

In [ ]:
merged_df_all6_1_1['New_Date'] = pd.to_datetime(merged_df_all6_1_1['New_Date'], format='%d %b %Y')

In [ ]:
df_sorted_df_all6_1_1 = merged_df_all6_1_1.sort_values('New_Date')

In [ ]:
df_sorted_df_all6_1_1

,New_Date,Balance,Details,Debit,Credit
35,2022-07-01,"$6,897.88 CR","Salary 9D Care,9D Care",NaN,$275.22
36,2022-07-04,"$6,998.48 CR","Direct Credit 074806 BUPA_CLM_CR-0407,C5703707...",NaN,$100.60
0,2022-07-05,"$6,780.80 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241",81.96,NaN
1,2022-07-05,"$6,835.77 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241",162.71,NaN
37,2022-07-05,"$6,862.76 CR","Return COSTCO WHOLESALE AUS MOORABBI,Card xx6241",NaN,$26.99
38,2022-07-06,"$11,780.80 CR","Transfer From A A LADEINDE,Part of Professiona...",NaN,"$5,000.00"
2,2022-07-07,"$11,780.50 CR","OFFICEWORKS 0348 KEYSBOROUGH AU AUS,Card xx624...",0.3,NaN
39,2022-07-07,"$11,841.58 CR","Salary Nextt Health PL,1020773/07/2022",NaN,$61.08
11,2022-07-12,"$11,763.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da...",78.0,NaN
10,2022-07-12,"$11,745.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da...",18.0,NaN
8,2022-07-12,"$11,700.56 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241",13.12,NaN
7,2022-07-12,"$11,682.79 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241",17.77,NaN
6,2022-07-12,"$11,666.51 CR",PREMIER POULTRY DANDEN DANDENONG AU,16.28,NaN
5,2022-07-12,"$11,647.06 CR","QANDI FRESH PTY LTD DANDENONG AU,Card xx6241",19.45,NaN
9,2022-07-12,"$11,713.68 CR","WOOLWORTHS 3806 CLAYTON AU AUS,Card xx6241,Val...",31.90,NaN
44,2022-07-13,"$15,016.78 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,"$1,605.62"
43,2022-07-13,"$13,411.16 CR","Salary Yooralla,0009308",NaN,$537.54
45,2022-07-13,"$15,708.16 CR","Salary HammondCare,20052",NaN,$694.06
42,2022-07-13,"$12,873.62 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,226.56"
12,2022-07-13,"$15,014.10 CR","Direct Debit 066429 Linkt Melbourne,48131845-7...",2.68,NaN
14,2022-07-14,"$11,465.29 CR","Transfer to xx7964 CommBank app,July sa","5,000.00",NaN
46,2022-07-14,"$16,465.29 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$757.13
47,2022-07-15,"$12,210.37 CR","Salary 9D Care,9D Care",NaN,$817.96
18,2022-07-15,"$11,454.24 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05,NaN
17,2022-07-15,"$11,443.19 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05,NaN
16,2022-07-15,"$11,392.41 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx...",50.78,NaN
30,2022-07-19,"$10,559.37 CR","WPNP PTY LTD NetBank BPAY 304303,1635571282 rent","1,651.00",NaN
28,2022-07-19,"$10,478.06 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05,NaN
29,2022-07-19,"$10,489.11 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx...",70.26,NaN
40,2023-01-11,"$10,846.41 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,"$2,778.82"
41,2023-01-11,"$8,067.59 CR","Salary Symmetry Human R,Symmetry HR W 1221",NaN,$893.76
3,2023-01-11,"$5,846.41 CR",Transfer to xx7964 CommBank app,"5,000.00",NaN
4,2023-01-12,"$5,246.41 CR","Transfer To Regeneration Church,CommBank App 6...",600.00,NaN
13,2023-01-14,"$5,190.36 CR","AA OFFCR OTBND7020 OFFICER SOUTH VI AUS,Card x...",56.05,NaN
15,2023-01-15,"$5,155.36 CR",T*M Tickets-CSS - Sat,35.00,NaN
19,2023-01-16,"$5,000.86 CR","Direct Debit 507533 SOUTH EAST WATER,DT.1bqjog...",62.00,NaN
20,2023-01-16,"$5,062.86 CR",HENRYS MERCATO WAVER MULGRAVE AU,50.22,NaN
21,2023-01-16,"$5,113.08 CR",PAT'S MUSIC OAKLEIGH SOUTVICAU,42.28,NaN
22,2023-01-17,"$4,650.86 CR",ANDRE J MENSWEAR CLAYTON VICAU,350.00,NaN
49,2023-01-18,"$5,758.65 CR","Salary Symmetry Human R,Symmetry HR W 1227",NaN,$382.57
24,2023-01-18,"$4,048.48 CR","Direct Debit 000793 BUPA AUSTRALIA,46484796000...",602.38,NaN
23,2023-01-18,"$4,005.98 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",42.50,NaN
48,2023-01-18,"$5,376.08 CR","Salary Symmetry Human R,Symmetry HR W 1227",NaN,"$1,370.10"
25,2023-01-19,"$5,650.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership",28.00,NaN
27,2023-01-19,"$5,706.22 CR","Direct Debit 157640 RACV INSURANCE,MOT73949596...",52.43,NaN
26,2023-01-19,"$5,678.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership",28.00,NaN
31,2023-01-21,"$5,607.92 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",42.30,NaN
33,2023-01-22,"$3,607.92 CR",Transfer to xx7964 CommBank app,"2,000.00",NaN
32,2023-01-22,"$1,957.02 CR","WPNP PTY LTD CommBank app BPAY 3,1635571282 rent","1,651.00",NaN
50,2023-01-22,"$3,608.02 CR","Fast Transfer From RENTPAY TECHNOLOGY PT,Accou...",NaN,$0.10
34,2023-01-24,"$1,924.32 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx569...",32.70,NaN

df_all6_1_2

In [ ]:
df_all6_1_2.head(51)

,Date Transaction,Unnamed: 0,Debit,Unnamed: 1,Credit,Balance
0,26 Apr 2023 OPENING BALANCE,NaN,NaN,NaN,NaN,"$4,942.30 CR"
1,26 Apr Fast Transfer From A A LADEINDE,NaN,NaN,NaN,NaN,NaN
2,move balance,NaN,NaN,NaN,$0.94,"$4,943.24 CR"
3,26 Apr Salary YNA,NaN,NaN,NaN,NaN,NaN
4,Payroll,NaN,NaN,NaN,"$1,131.32","$6,074.56 CR"
5,27 Apr AA CHADSTONE 0098 CHADSTONE VI AUS,NaN,NaN,NaN,NaN,NaN
6,Card xx5698,NaN,NaN,NaN,NaN,NaN
7,Value Date: 21/04/2023,NaN,96.46,(,NaN,"$5,978.10 CR"
8,27 Apr Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,NaN,NaN
9,HACSU78904,NaN,28.00,(,NaN,"$5,950.10 CR"
10,27 Apr Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,NaN,NaN
11,HACSU78903,NaN,28.00,(,NaN,"$5,922.10 CR"
12,28 Apr KFC ASHBURTON ASHBURTON AU,NaN,NaN,NaN,NaN,NaN
13,Card xx5698,NaN,16.35,(,NaN,"$5,905.75 CR"
14,28 Apr Transfer to xx7964 CommBank app,NaN,"3,000.00",(,NaN,"$2,905.75 CR"
15,29 Apr CellOPark Australia Matraville NS AUS,NaN,NaN,NaN,NaN,NaN
16,Card xx5698,NaN,NaN,NaN,NaN,NaN
17,Value Date: 27/04/2023,NaN,13.83,(,NaN,"$2,891.92 CR"
18,29 Apr SMP*Dominos Noble Park Noble Park03 AU,NaN,20.30,(,NaN,"$2,871.62 CR"
19,02 May Innovate1Pay Ltd Abuja NG NGA,NaN,NaN,NaN,NaN,NaN
20,Card xx6241 USD 77.00,NaN,NaN,NaN,NaN,NaN
21,Value Date: 24/04/2023,NaN,116.86,(,NaN,"$2,754.76 CR"
22,02 May International Transaction Fee,NaN,NaN,NaN,NaN,NaN
23,Value Date: 23/04/2023,NaN,3.51,(,NaN,"$2,751.25 CR"
24,02 May Innovate1Pay Ltd Abuja NG NGA,NaN,NaN,NaN,NaN,NaN
25,Card xx5698 USD 106.00,NaN,NaN,NaN,NaN,NaN
26,Value Date: 24/04/2023,NaN,160.87,(,NaN,"$2,590.38 CR"
27,02 May International Transaction Fee,NaN,NaN,NaN,NaN,NaN
28,Value Date: 23/04/2023,NaN,4.83,(,NaN,"$2,585.55 CR"
29,02 May Direct Debit 314011 AGL TELCO,NaN,NaN,NaN,NaN,NaN
30,PAYWAY3466657131,NaN,68.00,(,NaN,"$2,517.55 CR"
31,03 May Salary MONASH UNIVERSIT,NaN,NaN,NaN,NaN,NaN
32,SALARY 01163921,NaN,NaN,NaN,$599.65,"$3,117.20 CR"
33,03 May KFC ASHBURTON ASHBURTON AU,NaN,NaN,NaN,NaN,NaN
34,Card xx5698,NaN,16.45,(,NaN,"$3,100.75 CR"
35,03 May Salary MONASH UNIVERSIT,NaN,NaN,NaN,NaN,NaN
36,SALARY 01163158,NaN,NaN,NaN,"$1,264.89","$4,365.64 CR"
37,03 May Salary Yooralla,NaN,NaN,NaN,NaN,NaN
38,0009308,NaN,NaN,NaN,$970.98,"$5,336.62 CR"
39,03 May Salary YNA,NaN,NaN,NaN,NaN,NaN
40,Payroll,NaN,NaN,NaN,"$1,192.82","$6,529.44 CR"
41,03 May Salary Symmetry Human R,NaN,NaN,NaN,NaN,NaN
42,Symmetry HR W 1299,NaN,NaN,NaN,$58.18,"$6,587.62 CR"
43,03 May Direct Credit 621009 SmartSalary,NaN,NaN,NaN,NaN,NaN
44,GroupedSS,NaN,NaN,NaN,$703.56,"$7,291.18 CR"
45,04 May Transfer to xx7964 CommBank app,NaN,"3,000.00",(,NaN,"$4,291.18 CR"
46,04 May AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,NaN,NaN,NaN,NaN,NaN
47,Card xx5698,NaN,NaN,NaN,NaN,NaN
48,Value Date: 02/05/2023,NaN,100.00,(,NaN,"$4,191.18 CR"
49,04 May POST WAVERLEY GARDENS P VI AU,NaN,NaN,NaN,NaN,NaN
50,Card xx6241,NaN,46.69,(,NaN,"$4,144.49 CR"

In [ ]:
df_all6_1_2 = df_all6_1_2.drop(['Unnamed: 0','Unnamed: 1' ], axis=1)

In [ ]:
df_all6_1_2

,Date Transaction,Debit,Credit,Balance
0,26 Apr 2023 OPENING BALANCE,NaN,NaN,"$4,942.30 CR"
1,26 Apr Fast Transfer From A A LADEINDE,NaN,NaN,NaN
2,move balance,NaN,$0.94,"$4,943.24 CR"
3,26 Apr Salary YNA,NaN,NaN,NaN
4,Payroll,NaN,"$1,131.32","$6,074.56 CR"
...,...,...,...,...
82,10 Jan VICROADS CommBank app BPAY 2,NaN,NaN,NaN
83,528671080015065,864.40,NaN,"$3,315.71 CR"
84,10 Jan Direct Debit 066429 Linkt Melbourne,NaN,NaN,NaN
85,70746973-754237184,14.94,NaN,"$3,300.77 CR"
86,11 Jan PROUDS 132 MULGRAVE AU,71.90,NaN,"$3,228.87 CR"

In [ ]:
# used to split the values under date column e.g 02 Aug WOOLWORTHS 3940 CRANBOURNE W AU AUS
x = df_all6_1_2['Date Transaction'].str.extract(r'(\d+\s\w+)\s(.+)')
x[~x[0].isnull()].head(50)

           0                                        1
0     26 Apr                     2023 OPENING BALANCE
1     26 Apr          Fast Transfer From A A LADEINDE
3     26 Apr                               Salary YNA
5     27 Apr       AA CHADSTONE 0098 CHADSTONE VI AUS
8     27 Apr         Direct Debit 017325 HACSU VIC #2
10    27 Apr         Direct Debit 017325 HACSU VIC #2
12    28 Apr               KFC ASHBURTON ASHBURTON AU
14    28 Apr          Transfer to xx7964 CommBank app
15    29 Apr    CellOPark Australia Matraville NS AUS
18    29 Apr   SMP*Dominos Noble Park Noble Park03 AU
19    02 May            Innovate1Pay Ltd Abuja NG NGA
20  6241 USD                                    77.00
22    02 May            International Transaction Fee
24    02 May            Innovate1Pay Ltd Abuja NG NGA
25  5698 USD                                   106.00
27    02 May            International Transaction Fee
29    02 May            Direct Debit 314011 AGL TELCO
31    03 May                  Salary MONASH UNIVERSIT
33    03 May               KFC ASHBURTON ASHBURTON AU
35    03 May                  Salary MONASH UNIVERSIT
37    03 May                          Salary Yooralla
39    03 May                               Salary YNA
41    03 May                  Salary Symmetry Human R
43    03 May         Direct Credit 621009 SmartSalary
45    04 May          Transfer to xx7964 CommBank app
46    04 May     AMAYSIM MOBILE PTY LTD SYDNEY NS AUS
49    04 May            POST WAVERLEY GARDENS P VI AU
51    04 May            POST WAVERLEY GARDENS P VI AU
53    05 May             TOY WAVERLEY MULGRAVE VI AUS
56    05 May            POST WAVERLEY GARDENS P VI AU
58    05 May            POST WAVERLEY GARDENS P VI AU
60    05 May  Wdl ATM Red NP-Dandenong Mark Dandenong
61    05 May               Non CBA ATM Withdrawal Fee
62    05 May               SPOTTO VIC DARLINGHURST AU
63    05 May     Direct Debit 348045 AGL SALES PTY LT
65    06 May       BP DANDENONG 3940 DANDENONG VI AUS
68    31 Dec                     2022 OPENING BALANCE
69    03 Jan     Direct Debit 518073 Performance Educ
71    03 Jan            Direct Debit 314011 AGL TELCO
73    04 Jan                  Salary Symmetry Human R
75    04 Jan                  Salary Symmetry Human R
77    06 Jan               Transfer To Driving School
79    10 Jan       VICROADS PAKENHAMEAST PAKENHAM AUS
82    10 Jan             VICROADS CommBank app BPAY 2
84    10 Jan      Direct Debit 066429 Linkt Melbourne
86    11 Jan                   PROUDS 132 MULGRAVE AU

In [ ]:
# used to split the values under date column e.g 02 Aug WOOLWORTHS 3940 CRANBOURNE W AU AUS used it to create new columns 'New_Date', 'Details'
df_all6_1_2[['New_Date', 'Details']] = df_all6_1_2['Date Transaction'].str.extract(r'(\d+\s\w+)\s(.+)')

In [ ]:
df_all6_1_2['Details']= df_all6_1_2['Details'].fillna(df_all6_1_2[df_all6_1_2['Details'].isnull()]['Date Transaction'])

In [ ]:
df_all6_1_2.head(50)

,Date Transaction,Debit,Credit,Balance,New_Date,Details
0,26 Apr 2023 OPENING BALANCE,NaN,NaN,"$4,942.30 CR",26 Apr,2023 OPENING BALANCE
1,26 Apr Fast Transfer From A A LADEINDE,NaN,NaN,NaN,26 Apr,Fast Transfer From A A LADEINDE
2,move balance,NaN,$0.94,"$4,943.24 CR",NaN,move balance
3,26 Apr Salary YNA,NaN,NaN,NaN,26 Apr,Salary YNA
4,Payroll,NaN,"$1,131.32","$6,074.56 CR",NaN,Payroll
5,27 Apr AA CHADSTONE 0098 CHADSTONE VI AUS,NaN,NaN,NaN,27 Apr,AA CHADSTONE 0098 CHADSTONE VI AUS
6,Card xx5698,NaN,NaN,NaN,NaN,Card xx5698
7,Value Date: 21/04/2023,96.46,NaN,"$5,978.10 CR",NaN,Value Date: 21/04/2023
8,27 Apr Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,27 Apr,Direct Debit 017325 HACSU VIC #2
9,HACSU78904,28.00,NaN,"$5,950.10 CR",NaN,HACSU78904
10,27 Apr Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,27 Apr,Direct Debit 017325 HACSU VIC #2
11,HACSU78903,28.00,NaN,"$5,922.10 CR",NaN,HACSU78903
12,28 Apr KFC ASHBURTON ASHBURTON AU,NaN,NaN,NaN,28 Apr,KFC ASHBURTON ASHBURTON AU
13,Card xx5698,16.35,NaN,"$5,905.75 CR",NaN,Card xx5698
14,28 Apr Transfer to xx7964 CommBank app,"3,000.00",NaN,"$2,905.75 CR",28 Apr,Transfer to xx7964 CommBank app
15,29 Apr CellOPark Australia Matraville NS AUS,NaN,NaN,NaN,29 Apr,CellOPark Australia Matraville NS AUS
16,Card xx5698,NaN,NaN,NaN,NaN,Card xx5698
17,Value Date: 27/04/2023,13.83,NaN,"$2,891.92 CR",NaN,Value Date: 27/04/2023
18,29 Apr SMP*Dominos Noble Park Noble Park03 AU,20.30,NaN,"$2,871.62 CR",29 Apr,SMP*Dominos Noble Park Noble Park03 AU
19,02 May Innovate1Pay Ltd Abuja NG NGA,NaN,NaN,NaN,02 May,Innovate1Pay Ltd Abuja NG NGA
20,Card xx6241 USD 77.00,NaN,NaN,NaN,6241 USD,77.00
21,Value Date: 24/04/2023,116.86,NaN,"$2,754.76 CR",NaN,Value Date: 24/04/2023
22,02 May International Transaction Fee,NaN,NaN,NaN,02 May,International Transaction Fee
23,Value Date: 23/04/2023,3.51,NaN,"$2,751.25 CR",NaN,Value Date: 23/04/2023
24,02 May Innovate1Pay Ltd Abuja NG NGA,NaN,NaN,NaN,02 May,Innovate1Pay Ltd Abuja NG NGA
25,Card xx5698 USD 106.00,NaN,NaN,NaN,5698 USD,106.00
26,Value Date: 24/04/2023,160.87,NaN,"$2,590.38 CR",NaN,Value Date: 24/04/2023
27,02 May International Transaction Fee,NaN,NaN,NaN,02 May,International Transaction Fee
28,Value Date: 23/04/2023,4.83,NaN,"$2,585.55 CR",NaN,Value Date: 23/04/2023
29,02 May Direct Debit 314011 AGL TELCO,NaN,NaN,NaN,02 May,Direct Debit 314011 AGL TELCO
30,PAYWAY3466657131,68.00,NaN,"$2,517.55 CR",NaN,PAYWAY3466657131
31,03 May Salary MONASH UNIVERSIT,NaN,NaN,NaN,03 May,Salary MONASH UNIVERSIT
32,SALARY 01163921,NaN,$599.65,"$3,117.20 CR",NaN,SALARY 01163921
33,03 May KFC ASHBURTON ASHBURTON AU,NaN,NaN,NaN,03 May,KFC ASHBURTON ASHBURTON AU
34,Card xx5698,16.45,NaN,"$3,100.75 CR",NaN,Card xx5698
35,03 May Salary MONASH UNIVERSIT,NaN,NaN,NaN,03 May,Salary MONASH UNIVERSIT
36,SALARY 01163158,NaN,"$1,264.89","$4,365.64 CR",NaN,SALARY 01163158
37,03 May Salary Yooralla,NaN,NaN,NaN,03 May,Salary Yooralla
38,0009308,NaN,$970.98,"$5,336.62 CR",NaN,0009308
39,03 May Salary YNA,NaN,NaN,NaN,03 May,Salary YNA
40,Payroll,NaN,"$1,192.82","$6,529.44 CR",NaN,Payroll
41,03 May Salary Symmetry Human R,NaN,NaN,NaN,03 May,Salary Symmetry Human R
42,Symmetry HR W 1299,NaN,$58.18,"$6,587.62 CR",NaN,Symmetry HR W 1299
43,03 May Direct Credit 621009 SmartSalary,NaN,NaN,NaN,03 May,Direct Credit 621009 SmartSalary
44,GroupedSS,NaN,$703.56,"$7,291.18 CR",NaN,GroupedSS
45,04 May Transfer to xx7964 CommBank app,"3,000.00",NaN,"$4,291.18 CR",04 May,Transfer to xx7964 CommBank app
46,04 May AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,NaN,NaN,NaN,04 May,AMAYSIM MOBILE PTY LTD SYDNEY NS AUS
47,Card xx5698,NaN,NaN,NaN,NaN,Card xx5698
48,Value Date: 02/05/2023,100.00,NaN,"$4,191.18 CR",NaN,Value Date: 02/05/2023
49,04 May POST WAVERLEY GARDENS P VI AU,NaN,NaN,NaN,04 May,POST WAVERLEY GARDENS P VI AU

In [ ]:
df_all6_1_2.New_Date = df_all6_1_2.New_Date.ffill()

In [ ]:
df_all6_1_2

,Date Transaction,Debit,Credit,Balance,New_Date,Details
0,26 Apr 2023 OPENING BALANCE,NaN,NaN,"$4,942.30 CR",26 Apr,2023 OPENING BALANCE
1,26 Apr Fast Transfer From A A LADEINDE,NaN,NaN,NaN,26 Apr,Fast Transfer From A A LADEINDE
2,move balance,NaN,$0.94,"$4,943.24 CR",26 Apr,move balance
3,26 Apr Salary YNA,NaN,NaN,NaN,26 Apr,Salary YNA
4,Payroll,NaN,"$1,131.32","$6,074.56 CR",26 Apr,Payroll
...,...,...,...,...,...,...
82,10 Jan VICROADS CommBank app BPAY 2,NaN,NaN,NaN,10 Jan,VICROADS CommBank app BPAY 2
83,528671080015065,864.40,NaN,"$3,315.71 CR",10 Jan,528671080015065
84,10 Jan Direct Debit 066429 Linkt Melbourne,NaN,NaN,NaN,10 Jan,Direct Debit 066429 Linkt Melbourne
85,70746973-754237184,14.94,NaN,"$3,300.77 CR",10 Jan,70746973-754237184
86,11 Jan PROUDS 132 MULGRAVE AU,71.90,NaN,"$3,228.87 CR",11 Jan,PROUDS 132 MULGRAVE AU

In [ ]:
df_all6_1_2['New_Date'][~(df_all6_1_2['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)] = np.nan

<ipython-input-209-3292680b52cf>:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_all6_1_2['New_Date'][~(df_all6_1_2['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)] = np.nan

In [ ]:
df_all6_1_2['New_Date'][~(df_all6_1_2['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)]

<ipython-input-210-0ba1b69d64f9>:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_all6_1_2['New_Date'][~(df_all6_1_2['New_Date'].str.contains(r'(^\d\d\s[A-Za-z][A-Za-z][A-Za-z]$)') == True)]

20    NaN
21    NaN
25    NaN
26    NaN
Name: New_Date, dtype: object

In [ ]:
df_all6_1_2.New_Date = df_all6_1_2.New_Date.ffill()

In [ ]:
df_all6_1_2.head(50)

,Date Transaction,Debit,Credit,Balance,New_Date,Details
0,26 Apr 2023 OPENING BALANCE,NaN,NaN,"$4,942.30 CR",26 Apr,2023 OPENING BALANCE
1,26 Apr Fast Transfer From A A LADEINDE,NaN,NaN,NaN,26 Apr,Fast Transfer From A A LADEINDE
2,move balance,NaN,$0.94,"$4,943.24 CR",26 Apr,move balance
3,26 Apr Salary YNA,NaN,NaN,NaN,26 Apr,Salary YNA
4,Payroll,NaN,"$1,131.32","$6,074.56 CR",26 Apr,Payroll
5,27 Apr AA CHADSTONE 0098 CHADSTONE VI AUS,NaN,NaN,NaN,27 Apr,AA CHADSTONE 0098 CHADSTONE VI AUS
6,Card xx5698,NaN,NaN,NaN,27 Apr,Card xx5698
7,Value Date: 21/04/2023,96.46,NaN,"$5,978.10 CR",27 Apr,Value Date: 21/04/2023
8,27 Apr Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,27 Apr,Direct Debit 017325 HACSU VIC #2
9,HACSU78904,28.00,NaN,"$5,950.10 CR",27 Apr,HACSU78904
10,27 Apr Direct Debit 017325 HACSU VIC #2,NaN,NaN,NaN,27 Apr,Direct Debit 017325 HACSU VIC #2
11,HACSU78903,28.00,NaN,"$5,922.10 CR",27 Apr,HACSU78903
12,28 Apr KFC ASHBURTON ASHBURTON AU,NaN,NaN,NaN,28 Apr,KFC ASHBURTON ASHBURTON AU
13,Card xx5698,16.35,NaN,"$5,905.75 CR",28 Apr,Card xx5698
14,28 Apr Transfer to xx7964 CommBank app,"3,000.00",NaN,"$2,905.75 CR",28 Apr,Transfer to xx7964 CommBank app
15,29 Apr CellOPark Australia Matraville NS AUS,NaN,NaN,NaN,29 Apr,CellOPark Australia Matraville NS AUS
16,Card xx5698,NaN,NaN,NaN,29 Apr,Card xx5698
17,Value Date: 27/04/2023,13.83,NaN,"$2,891.92 CR",29 Apr,Value Date: 27/04/2023
18,29 Apr SMP*Dominos Noble Park Noble Park03 AU,20.30,NaN,"$2,871.62 CR",29 Apr,SMP*Dominos Noble Park Noble Park03 AU
19,02 May Innovate1Pay Ltd Abuja NG NGA,NaN,NaN,NaN,02 May,Innovate1Pay Ltd Abuja NG NGA
20,Card xx6241 USD 77.00,NaN,NaN,NaN,02 May,77.00
21,Value Date: 24/04/2023,116.86,NaN,"$2,754.76 CR",02 May,Value Date: 24/04/2023
22,02 May International Transaction Fee,NaN,NaN,NaN,02 May,International Transaction Fee
23,Value Date: 23/04/2023,3.51,NaN,"$2,751.25 CR",02 May,Value Date: 23/04/2023
24,02 May Innovate1Pay Ltd Abuja NG NGA,NaN,NaN,NaN,02 May,Innovate1Pay Ltd Abuja NG NGA
25,Card xx5698 USD 106.00,NaN,NaN,NaN,02 May,106.00
26,Value Date: 24/04/2023,160.87,NaN,"$2,590.38 CR",02 May,Value Date: 24/04/2023
27,02 May International Transaction Fee,NaN,NaN,NaN,02 May,International Transaction Fee
28,Value Date: 23/04/2023,4.83,NaN,"$2,585.55 CR",02 May,Value Date: 23/04/2023
29,02 May Direct Debit 314011 AGL TELCO,NaN,NaN,NaN,02 May,Direct Debit 314011 AGL TELCO
30,PAYWAY3466657131,68.00,NaN,"$2,517.55 CR",02 May,PAYWAY3466657131
31,03 May Salary MONASH UNIVERSIT,NaN,NaN,NaN,03 May,Salary MONASH UNIVERSIT
32,SALARY 01163921,NaN,$599.65,"$3,117.20 CR",03 May,SALARY 01163921
33,03 May KFC ASHBURTON ASHBURTON AU,NaN,NaN,NaN,03 May,KFC ASHBURTON ASHBURTON AU
34,Card xx5698,16.45,NaN,"$3,100.75 CR",03 May,Card xx5698
35,03 May Salary MONASH UNIVERSIT,NaN,NaN,NaN,03 May,Salary MONASH UNIVERSIT
36,SALARY 01163158,NaN,"$1,264.89","$4,365.64 CR",03 May,SALARY 01163158
37,03 May Salary Yooralla,NaN,NaN,NaN,03 May,Salary Yooralla
38,0009308,NaN,$970.98,"$5,336.62 CR",03 May,0009308
39,03 May Salary YNA,NaN,NaN,NaN,03 May,Salary YNA
40,Payroll,NaN,"$1,192.82","$6,529.44 CR",03 May,Payroll
41,03 May Salary Symmetry Human R,NaN,NaN,NaN,03 May,Salary Symmetry Human R
42,Symmetry HR W 1299,NaN,$58.18,"$6,587.62 CR",03 May,Symmetry HR W 1299
43,03 May Direct Credit 621009 SmartSalary,NaN,NaN,NaN,03 May,Direct Credit 621009 SmartSalary
44,GroupedSS,NaN,$703.56,"$7,291.18 CR",03 May,GroupedSS
45,04 May Transfer to xx7964 CommBank app,"3,000.00",NaN,"$4,291.18 CR",04 May,Transfer to xx7964 CommBank app
46,04 May AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,NaN,NaN,NaN,04 May,AMAYSIM MOBILE PTY LTD SYDNEY NS AUS
47,Card xx5698,NaN,NaN,NaN,04 May,Card xx5698
48,Value Date: 02/05/2023,100.00,NaN,"$4,191.18 CR",04 May,Value Date: 02/05/2023
49,04 May POST WAVERLEY GARDENS P VI AU,NaN,NaN,NaN,04 May,POST WAVERLEY GARDENS P VI AU

In [ ]:
df_all6_1_2.Balance = df_all6_1_2.Balance.bfill()

In [ ]:
df_all6_1_2

,Date Transaction,Debit,Credit,Balance,New_Date,Details
0,26 Apr 2023 OPENING BALANCE,NaN,NaN,"$4,942.30 CR",26 Apr,2023 OPENING BALANCE
1,26 Apr Fast Transfer From A A LADEINDE,NaN,NaN,"$4,943.24 CR",26 Apr,Fast Transfer From A A LADEINDE
2,move balance,NaN,$0.94,"$4,943.24 CR",26 Apr,move balance
3,26 Apr Salary YNA,NaN,NaN,"$6,074.56 CR",26 Apr,Salary YNA
4,Payroll,NaN,"$1,131.32","$6,074.56 CR",26 Apr,Payroll
...,...,...,...,...,...,...
82,10 Jan VICROADS CommBank app BPAY 2,NaN,NaN,"$3,315.71 CR",10 Jan,VICROADS CommBank app BPAY 2
83,528671080015065,864.40,NaN,"$3,315.71 CR",10 Jan,528671080015065
84,10 Jan Direct Debit 066429 Linkt Melbourne,NaN,NaN,"$3,300.77 CR",10 Jan,Direct Debit 066429 Linkt Melbourne
85,70746973-754237184,14.94,NaN,"$3,300.77 CR",10 Jan,70746973-754237184
86,11 Jan PROUDS 132 MULGRAVE AU,71.90,NaN,"$3,228.87 CR",11 Jan,PROUDS 132 MULGRAVE AU

In [ ]:
new_df_all6_1_2 = df_all6_1_2[['New_Date','Details','Balance']]

In [ ]:
new_df_all6_1_2

   New_Date                              Details       Balance
0    26 Apr                 2023 OPENING BALANCE  $4,942.30 CR
1    26 Apr      Fast Transfer From A A LADEINDE  $4,943.24 CR
2    26 Apr                         move balance  $4,943.24 CR
3    26 Apr                           Salary YNA  $6,074.56 CR
4    26 Apr                              Payroll  $6,074.56 CR
..      ...                                  ...           ...
82   10 Jan         VICROADS CommBank app BPAY 2  $3,315.71 CR
83   10 Jan                      528671080015065  $3,315.71 CR
84   10 Jan  Direct Debit 066429 Linkt Melbourne  $3,300.77 CR
85   10 Jan                   70746973-754237184  $3,300.77 CR
86   11 Jan               PROUDS 132 MULGRAVE AU  $3,228.87 CR

[87 rows x 3 columns]

In [ ]:
#trying to append appropriate dates to the details of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_new_df_all6_1_2_2022 = new_df_all6_1_2[new_df_all6_1_2['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_2_2022['New_Date'] = filtered_new_df_all6_1_2_2022['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_new_df_all6_1_2_2023 = new_df_all6_1_2[new_df_all6_1_2['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_2_2023['New_Date'] = filtered_new_df_all6_1_2_2023['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenatednew_df_all6_1_2_df = pd.concat([filtered_new_df_all6_1_2_2022, filtered_new_df_all6_1_2_2023])

concatenatednew_df_all6_1_2_df

<ipython-input-217-50a341669eca>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_2_2022['New_Date'] = filtered_new_df_all6_1_2_2022['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-217-50a341669eca>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_2_2023['New_Date'] = filtered_new_df_all6_1_2_2023['New_Date'] + ' ' + year_to_concat_2023

       New_Date                              Details       Balance
68  31 Dec 2022                 2022 OPENING BALANCE  $4,751.11 CR
0   26 Apr 2023                 2023 OPENING BALANCE  $4,942.30 CR
1   26 Apr 2023      Fast Transfer From A A LADEINDE  $4,943.24 CR
2   26 Apr 2023                         move balance  $4,943.24 CR
3   26 Apr 2023                           Salary YNA  $6,074.56 CR
..          ...                                  ...           ...
82  10 Jan 2023         VICROADS CommBank app BPAY 2  $3,315.71 CR
83  10 Jan 2023                      528671080015065  $3,315.71 CR
84  10 Jan 2023  Direct Debit 066429 Linkt Melbourne  $3,300.77 CR
85  10 Jan 2023                   70746973-754237184  $3,300.77 CR
86  11 Jan 2023               PROUDS 132 MULGRAVE AU  $3,228.87 CR

[87 rows x 3 columns]

In [ ]:
#Grouping the dataframe by 'New_Date','Balance' as they are unique for each transaction
merged_df_all6_1_2_df_Details = concatenatednew_df_all6_1_2_df.groupby(['New_Date','Balance'])['Details'].agg(lambda x: ','.join(map(str, x))).reset_index()

In [ ]:
merged_df_all6_1_2_df_Details

,New_Date,Balance,Details
0,02 May 2023,"$2,517.55 CR","Direct Debit 314011 AGL TELCO,PAYWAY3466657131"
1,02 May 2023,"$2,585.55 CR","International Transaction Fee,Value Date: 23/0..."
2,02 May 2023,"$2,590.38 CR","Innovate1Pay Ltd Abuja NG NGA,106.00,Value Dat..."
3,02 May 2023,"$2,751.25 CR","International Transaction Fee,Value Date: 23/0..."
4,02 May 2023,"$2,754.76 CR","Innovate1Pay Ltd Abuja NG NGA,77.00,Value Date..."
5,03 Jan 2023,"$3,456.79 CR","Direct Debit 314011 AGL TELCO,PAYWAY3379077714"
6,03 Jan 2023,"$3,524.79 CR","Direct Debit 518073 Performance Educ,EZYPAYID ..."
7,03 May 2023,"$3,100.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698"
8,03 May 2023,"$3,117.20 CR","Salary MONASH UNIVERSIT,SALARY 01163921"
9,03 May 2023,"$4,365.64 CR","Salary MONASH UNIVERSIT,SALARY 01163158"
10,03 May 2023,"$5,336.62 CR","Salary Yooralla,0009308"
11,03 May 2023,"$6,529.44 CR","Salary YNA,Payroll"
12,03 May 2023,"$6,587.62 CR","Salary Symmetry Human R,Symmetry HR W 1299"
13,03 May 2023,"$7,291.18 CR","Direct Credit 621009 SmartSalary,GroupedSS"
14,04 Jan 2023,"$3,766.57 CR","Salary Symmetry Human R,Symmetry HR W 1215"
15,04 Jan 2023,"$4,734.49 CR","Salary Symmetry Human R,Symmetry HR W 1215"
16,04 May 2023,"$4,131.94 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241"
17,04 May 2023,"$4,144.49 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241"
18,04 May 2023,"$4,191.18 CR","AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,Card xx56..."
19,04 May 2023,"$4,291.18 CR",Transfer to xx7964 CommBank app
20,05 May 2023,"$3,112.68 CR","Direct Debit 348045 AGL SALES PTY LT,160009533332"
21,05 May 2023,"$3,222.27 CR",SPOTTO VIC DARLINGHURST AU
22,05 May 2023,"$3,256.59 CR",Non CBA ATM Withdrawal Fee
23,05 May 2023,"$3,259.39 CR",Wdl ATM Red NP-Dandenong Mark Dandenong
24,05 May 2023,"$3,459.39 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241"
25,05 May 2023,"$3,462.34 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241"
26,05 May 2023,"$3,471.94 CR","TOY WAVERLEY MULGRAVE VI AUS,Card xx6241,Value..."
27,06 Jan 2023,"$4,474.49 CR","Transfer To Driving School,CommBank App drivin..."
28,06 May 2023,"$3,014.27 CR","BP DANDENONG 3940 DANDENONG VI AUS,Card xx5698..."
29,10 Jan 2023,"$3,300.77 CR","Direct Debit 066429 Linkt Melbourne,70746973-7..."
30,10 Jan 2023,"$3,315.71 CR","VICROADS CommBank app BPAY 2,528671080015065"
31,10 Jan 2023,"$4,180.11 CR","VICROADS PAKENHAMEAST PAKENHAM AUS,Card xx6241..."
32,11 Jan 2023,"$3,228.87 CR",PROUDS 132 MULGRAVE AU
33,26 Apr 2023,"$4,942.30 CR",2023 OPENING BALANCE
34,26 Apr 2023,"$4,943.24 CR","Fast Transfer From A A LADEINDE,move balance"
35,26 Apr 2023,"$6,074.56 CR","Salary YNA,Payroll"
36,27 Apr 2023,"$5,922.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78903"
37,27 Apr 2023,"$5,950.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78904"
38,27 Apr 2023,"$5,978.10 CR","AA CHADSTONE 0098 CHADSTONE VI AUS,Card xx5698..."
39,28 Apr 2023,"$2,905.75 CR",Transfer to xx7964 CommBank app
40,28 Apr 2023,"$5,905.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698"
41,29 Apr 2023,"$2,871.62 CR",SMP*Dominos Noble Park Noble Park03 AU
42,29 Apr 2023,"$2,891.92 CR","CellOPark Australia Matraville NS AUS,Card xx5..."
43,31 Dec 2022,"$4,751.11 CR",2022 OPENING BALANCE

In [ ]:
new_df_all6_1_2_Credit = df_all6_1_2[['New_Date','Balance','Credit']]
new_df_all6_1_2_Debit = df_all6_1_2[['New_Date','Balance','Debit']]

In [ ]:
new_df_all6_1_2_Credit

   New_Date       Balance     Credit
0    26 Apr  $4,942.30 CR        NaN
1    26 Apr  $4,943.24 CR        NaN
2    26 Apr  $4,943.24 CR      $0.94
3    26 Apr  $6,074.56 CR        NaN
4    26 Apr  $6,074.56 CR  $1,131.32
..      ...           ...        ...
82   10 Jan  $3,315.71 CR        NaN
83   10 Jan  $3,315.71 CR        NaN
84   10 Jan  $3,300.77 CR        NaN
85   10 Jan  $3,300.77 CR        NaN
86   11 Jan  $3,228.87 CR        NaN

[87 rows x 3 columns]

In [ ]:
#trying to append appropriate dates to the details of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_new_df_all6_1_2_2022_Credit = new_df_all6_1_2_Credit[new_df_all6_1_2_Credit['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_2_2022_Credit['New_Date'] = filtered_new_df_all6_1_2_2022_Credit['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_new_df_all6_1_2_2023_Credit = new_df_all6_1_2_Credit[new_df_all6_1_2_Credit['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_2_2023_Credit['New_Date'] = filtered_new_df_all6_1_2_2023_Credit['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenatednew_df_all6_1_2_df_Credit = pd.concat([filtered_new_df_all6_1_2_2022_Credit, filtered_new_df_all6_1_2_2023_Credit])

concatenatednew_df_all6_1_2_df_Credit

<ipython-input-222-c0923a6a3df4>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_2_2022_Credit['New_Date'] = filtered_new_df_all6_1_2_2022_Credit['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-222-c0923a6a3df4>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_2_2023_Credit['New_Date'] = filtered_new_df_all6_1_2_2023_Credit['New_Date'] + ' ' + year_to_concat_2023

       New_Date       Balance Credit
68  31 Dec 2022  $4,751.11 CR    NaN
0   26 Apr 2023  $4,942.30 CR    NaN
1   26 Apr 2023  $4,943.24 CR    NaN
2   26 Apr 2023  $4,943.24 CR  $0.94
3   26 Apr 2023  $6,074.56 CR    NaN
..          ...           ...    ...
82  10 Jan 2023  $3,315.71 CR    NaN
83  10 Jan 2023  $3,315.71 CR    NaN
84  10 Jan 2023  $3,300.77 CR    NaN
85  10 Jan 2023  $3,300.77 CR    NaN
86  11 Jan 2023  $3,228.87 CR    NaN

[87 rows x 3 columns]

In [ ]:
#filtering the nans in the credit transactions dataframe
filtered_concatenatednew_df_all6_1_2_df_Credit = concatenatednew_df_all6_1_2_df_Credit[~concatenatednew_df_all6_1_2_df_Credit['Credit'].isnull()]
filtered_concatenatednew_df_all6_1_2_df_Credit

       New_Date       Balance     Credit
2   26 Apr 2023  $4,943.24 CR      $0.94
4   26 Apr 2023  $6,074.56 CR  $1,131.32
32  03 May 2023  $3,117.20 CR    $599.65
36  03 May 2023  $4,365.64 CR  $1,264.89
38  03 May 2023  $5,336.62 CR    $970.98
40  03 May 2023  $6,529.44 CR  $1,192.82
42  03 May 2023  $6,587.62 CR     $58.18
44  03 May 2023  $7,291.18 CR    $703.56
74  04 Jan 2023  $3,766.57 CR    $309.78
76  04 Jan 2023  $4,734.49 CR    $967.92

In [ ]:
#merger the credit data that had been filted for the values only with the
merged_df_Credit_all6_1_2_df = merged_df_all6_1_2_df_Details.merge(filtered_concatenatednew_df_all6_1_2_df_Credit, on=['New_Date', 'Balance'], how='inner')
merged_df_Credit_all6_1_2_df

,New_Date,Balance,Details,Credit
0,03 May 2023,"$3,117.20 CR","Salary MONASH UNIVERSIT,SALARY 01163921",$599.65
1,03 May 2023,"$4,365.64 CR","Salary MONASH UNIVERSIT,SALARY 01163158","$1,264.89"
2,03 May 2023,"$5,336.62 CR","Salary Yooralla,0009308",$970.98
3,03 May 2023,"$6,529.44 CR","Salary YNA,Payroll","$1,192.82"
4,03 May 2023,"$6,587.62 CR","Salary Symmetry Human R,Symmetry HR W 1299",$58.18
5,03 May 2023,"$7,291.18 CR","Direct Credit 621009 SmartSalary,GroupedSS",$703.56
6,04 Jan 2023,"$3,766.57 CR","Salary Symmetry Human R,Symmetry HR W 1215",$309.78
7,04 Jan 2023,"$4,734.49 CR","Salary Symmetry Human R,Symmetry HR W 1215",$967.92
8,26 Apr 2023,"$4,943.24 CR","Fast Transfer From A A LADEINDE,move balance",$0.94
9,26 Apr 2023,"$6,074.56 CR","Salary YNA,Payroll","$1,131.32"

In [ ]:
new_df_all6_1_2_Debit

   New_Date       Balance   Debit
0    26 Apr  $4,942.30 CR     NaN
1    26 Apr  $4,943.24 CR     NaN
2    26 Apr  $4,943.24 CR     NaN
3    26 Apr  $6,074.56 CR     NaN
4    26 Apr  $6,074.56 CR     NaN
..      ...           ...     ...
82   10 Jan  $3,315.71 CR     NaN
83   10 Jan  $3,315.71 CR  864.40
84   10 Jan  $3,300.77 CR     NaN
85   10 Jan  $3,300.77 CR   14.94
86   11 Jan  $3,228.87 CR   71.90

[87 rows x 3 columns]

In [ ]:
#trying to append appropriate dates to the details of each transaction
# Define the search strings
search_strings_2022 = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
search_strings_2023 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Create a regular expression pattern
pattern_2022 = '|'.join(search_strings_2022)
pattern_2023 = '|'.join(search_strings_2023)

# Specify the year to concatenate
year_to_concat_2022 = '2022'
year_to_concat_2023 = '2023'

# Filter 'Date' column for values containing any of the search strings for 2022
filtered_new_df_all6_1_2_2022_Debit = new_df_all6_1_2_Debit[new_df_all6_1_2_Debit['New_Date'].str.contains(pattern_2022)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_2_2022_Debit['New_Date'] = filtered_new_df_all6_1_2_2022_Debit['New_Date'] + ' ' + year_to_concat_2022

# Filter 'Date' column for values containing any of the search strings for 2023
filtered_new_df_all6_1_2_2023_Debit = new_df_all6_1_2_Debit[new_df_all6_1_2_Debit['New_Date'].str.contains(pattern_2023)]

# Concatenate the year to the existing date
filtered_new_df_all6_1_2_2023_Debit['New_Date'] = filtered_new_df_all6_1_2_2023_Debit['New_Date'] + ' ' + year_to_concat_2023


# Concatenate the modified DataFrames
concatenatednew_df_all6_1_2_df_Debit = pd.concat([filtered_new_df_all6_1_2_2022_Debit, filtered_new_df_all6_1_2_2023_Debit])

concatenatednew_df_all6_1_2_df_Debit

<ipython-input-227-bff1c601dd46>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_2_2022_Debit['New_Date'] = filtered_new_df_all6_1_2_2022_Debit['New_Date'] + ' ' + year_to_concat_2022
<ipython-input-227-bff1c601dd46>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_new_df_all6_1_2_2023_Debit['New_Date'] = filtered_new_df_all6_1_2_2023_Debit['New_Date'] + ' ' + year_to_concat_2023

       New_Date       Balance   Debit
68  31 Dec 2022  $4,751.11 CR     NaN
0   26 Apr 2023  $4,942.30 CR     NaN
1   26 Apr 2023  $4,943.24 CR     NaN
2   26 Apr 2023  $4,943.24 CR     NaN
3   26 Apr 2023  $6,074.56 CR     NaN
..          ...           ...     ...
82  10 Jan 2023  $3,315.71 CR     NaN
83  10 Jan 2023  $3,315.71 CR  864.40
84  10 Jan 2023  $3,300.77 CR     NaN
85  10 Jan 2023  $3,300.77 CR   14.94
86  11 Jan 2023  $3,228.87 CR   71.90

[87 rows x 3 columns]

In [ ]:
#filtering the nans in the credit transactions dataframe
filtered_concatenatednew_df_all6_1_2_df_Debit = concatenatednew_df_all6_1_2_df_Debit[~concatenatednew_df_all6_1_2_df_Debit['Debit'].isnull()]
filtered_concatenatednew_df_all6_1_2_df_Debit

       New_Date       Balance     Debit
7   27 Apr 2023  $5,978.10 CR     96.46
9   27 Apr 2023  $5,950.10 CR     28.00
11  27 Apr 2023  $5,922.10 CR     28.00
13  28 Apr 2023  $5,905.75 CR     16.35
14  28 Apr 2023  $2,905.75 CR  3,000.00
17  29 Apr 2023  $2,891.92 CR     13.83
18  29 Apr 2023  $2,871.62 CR     20.30
21  02 May 2023  $2,754.76 CR    116.86
23  02 May 2023  $2,751.25 CR      3.51
26  02 May 2023  $2,590.38 CR    160.87
28  02 May 2023  $2,585.55 CR      4.83
30  02 May 2023  $2,517.55 CR     68.00
34  03 May 2023  $3,100.75 CR     16.45
45  04 May 2023  $4,291.18 CR  3,000.00
48  04 May 2023  $4,191.18 CR    100.00
50  04 May 2023  $4,144.49 CR     46.69
52  04 May 2023  $4,131.94 CR     12.55
55  05 May 2023  $3,471.94 CR    660.00
57  05 May 2023  $3,462.34 CR      9.60
59  05 May 2023  $3,459.39 CR      2.95
60  05 May 2023  $3,259.39 CR    200.00
61  05 May 2023  $3,256.59 CR      2.80
62  05 May 2023  $3,222.27 CR     34.32
64  05 May 2023  $3,112.68 CR    109.59
67  06 May 2023  $3,014.27 CR     98.41
70  03 Jan 2023  $3,524.79 CR  1,226.32
72  03 Jan 2023  $3,456.79 CR     68.00
78  06 Jan 2023  $4,474.49 CR    260.00
81  10 Jan 2023  $4,180.11 CR    294.38
83  10 Jan 2023  $3,315.71 CR    864.40
85  10 Jan 2023  $3,300.77 CR     14.94
86  11 Jan 2023  $3,228.87 CR     71.90

In [ ]:
#merger the credit data that had been filted for the values only with the
merged_df_Debit_all6_1_2_df = merged_df_all6_1_2_df_Details.merge(filtered_concatenatednew_df_all6_1_2_df_Debit, on=['New_Date', 'Balance'], how='inner')
merged_df_Debit_all6_1_2_df

,New_Date,Balance,Details,Debit
0,02 May 2023,"$2,517.55 CR","Direct Debit 314011 AGL TELCO,PAYWAY3466657131",68.00
1,02 May 2023,"$2,585.55 CR","International Transaction Fee,Value Date: 23/0...",4.83
2,02 May 2023,"$2,590.38 CR","Innovate1Pay Ltd Abuja NG NGA,106.00,Value Dat...",160.87
3,02 May 2023,"$2,751.25 CR","International Transaction Fee,Value Date: 23/0...",3.51
4,02 May 2023,"$2,754.76 CR","Innovate1Pay Ltd Abuja NG NGA,77.00,Value Date...",116.86
5,03 Jan 2023,"$3,456.79 CR","Direct Debit 314011 AGL TELCO,PAYWAY3379077714",68.00
6,03 Jan 2023,"$3,524.79 CR","Direct Debit 518073 Performance Educ,EZYPAYID ...","1,226.32"
7,03 May 2023,"$3,100.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.45
8,04 May 2023,"$4,131.94 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",12.55
9,04 May 2023,"$4,144.49 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",46.69
10,04 May 2023,"$4,191.18 CR","AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,Card xx56...",100.00
11,04 May 2023,"$4,291.18 CR",Transfer to xx7964 CommBank app,"3,000.00"
12,05 May 2023,"$3,112.68 CR","Direct Debit 348045 AGL SALES PTY LT,160009533332",109.59
13,05 May 2023,"$3,222.27 CR",SPOTTO VIC DARLINGHURST AU,34.32
14,05 May 2023,"$3,256.59 CR",Non CBA ATM Withdrawal Fee,2.80
15,05 May 2023,"$3,259.39 CR",Wdl ATM Red NP-Dandenong Mark Dandenong,200.00
16,05 May 2023,"$3,459.39 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",2.95
17,05 May 2023,"$3,462.34 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",9.60
18,05 May 2023,"$3,471.94 CR","TOY WAVERLEY MULGRAVE VI AUS,Card xx6241,Value...",660.00
19,06 Jan 2023,"$4,474.49 CR","Transfer To Driving School,CommBank App drivin...",260.00
20,06 May 2023,"$3,014.27 CR","BP DANDENONG 3940 DANDENONG VI AUS,Card xx5698...",98.41
21,10 Jan 2023,"$3,300.77 CR","Direct Debit 066429 Linkt Melbourne,70746973-7...",14.94
22,10 Jan 2023,"$3,315.71 CR","VICROADS CommBank app BPAY 2,528671080015065",864.40
23,10 Jan 2023,"$4,180.11 CR","VICROADS PAKENHAMEAST PAKENHAM AUS,Card xx6241...",294.38
24,11 Jan 2023,"$3,228.87 CR",PROUDS 132 MULGRAVE AU,71.90
25,27 Apr 2023,"$5,922.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78903",28.00
26,27 Apr 2023,"$5,950.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78904",28.00
27,27 Apr 2023,"$5,978.10 CR","AA CHADSTONE 0098 CHADSTONE VI AUS,Card xx5698...",96.46
28,28 Apr 2023,"$2,905.75 CR",Transfer to xx7964 CommBank app,"3,000.00"
29,28 Apr 2023,"$5,905.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.35
30,29 Apr 2023,"$2,871.62 CR",SMP*Dominos Noble Park Noble Park03 AU,20.30
31,29 Apr 2023,"$2,891.92 CR","CellOPark Australia Matraville NS AUS,Card xx5...",13.83

In [ ]:
merged_df_all6_1_2 = pd.concat([ merged_df_Debit_all6_1_2_df , merged_df_Credit_all6_1_2_df], ignore_index=True)

In [ ]:
merged_df_all6_1_2

,New_Date,Balance,Details,Debit,Credit
0,02 May 2023,"$2,517.55 CR","Direct Debit 314011 AGL TELCO,PAYWAY3466657131",68.00,NaN
1,02 May 2023,"$2,585.55 CR","International Transaction Fee,Value Date: 23/0...",4.83,NaN
2,02 May 2023,"$2,590.38 CR","Innovate1Pay Ltd Abuja NG NGA,106.00,Value Dat...",160.87,NaN
3,02 May 2023,"$2,751.25 CR","International Transaction Fee,Value Date: 23/0...",3.51,NaN
4,02 May 2023,"$2,754.76 CR","Innovate1Pay Ltd Abuja NG NGA,77.00,Value Date...",116.86,NaN
5,03 Jan 2023,"$3,456.79 CR","Direct Debit 314011 AGL TELCO,PAYWAY3379077714",68.00,NaN
6,03 Jan 2023,"$3,524.79 CR","Direct Debit 518073 Performance Educ,EZYPAYID ...","1,226.32",NaN
7,03 May 2023,"$3,100.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.45,NaN
8,04 May 2023,"$4,131.94 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",12.55,NaN
9,04 May 2023,"$4,144.49 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",46.69,NaN
10,04 May 2023,"$4,191.18 CR","AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,Card xx56...",100.00,NaN
11,04 May 2023,"$4,291.18 CR",Transfer to xx7964 CommBank app,"3,000.00",NaN
12,05 May 2023,"$3,112.68 CR","Direct Debit 348045 AGL SALES PTY LT,160009533332",109.59,NaN
13,05 May 2023,"$3,222.27 CR",SPOTTO VIC DARLINGHURST AU,34.32,NaN
14,05 May 2023,"$3,256.59 CR",Non CBA ATM Withdrawal Fee,2.80,NaN
15,05 May 2023,"$3,259.39 CR",Wdl ATM Red NP-Dandenong Mark Dandenong,200.00,NaN
16,05 May 2023,"$3,459.39 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",2.95,NaN
17,05 May 2023,"$3,462.34 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",9.60,NaN
18,05 May 2023,"$3,471.94 CR","TOY WAVERLEY MULGRAVE VI AUS,Card xx6241,Value...",660.00,NaN
19,06 Jan 2023,"$4,474.49 CR","Transfer To Driving School,CommBank App drivin...",260.00,NaN
20,06 May 2023,"$3,014.27 CR","BP DANDENONG 3940 DANDENONG VI AUS,Card xx5698...",98.41,NaN
21,10 Jan 2023,"$3,300.77 CR","Direct Debit 066429 Linkt Melbourne,70746973-7...",14.94,NaN
22,10 Jan 2023,"$3,315.71 CR","VICROADS CommBank app BPAY 2,528671080015065",864.40,NaN
23,10 Jan 2023,"$4,180.11 CR","VICROADS PAKENHAMEAST PAKENHAM AUS,Card xx6241...",294.38,NaN
24,11 Jan 2023,"$3,228.87 CR",PROUDS 132 MULGRAVE AU,71.90,NaN
25,27 Apr 2023,"$5,922.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78903",28.00,NaN
26,27 Apr 2023,"$5,950.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78904",28.00,NaN
27,27 Apr 2023,"$5,978.10 CR","AA CHADSTONE 0098 CHADSTONE VI AUS,Card xx5698...",96.46,NaN
28,28 Apr 2023,"$2,905.75 CR",Transfer to xx7964 CommBank app,"3,000.00",NaN
29,28 Apr 2023,"$5,905.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.35,NaN
30,29 Apr 2023,"$2,871.62 CR",SMP*Dominos Noble Park Noble Park03 AU,20.30,NaN
31,29 Apr 2023,"$2,891.92 CR","CellOPark Australia Matraville NS AUS,Card xx5...",13.83,NaN
32,03 May 2023,"$3,117.20 CR","Salary MONASH UNIVERSIT,SALARY 01163921",NaN,$599.65
33,03 May 2023,"$4,365.64 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,264.89"
34,03 May 2023,"$5,336.62 CR","Salary Yooralla,0009308",NaN,$970.98
35,03 May 2023,"$6,529.44 CR","Salary YNA,Payroll",NaN,"$1,192.82"
36,03 May 2023,"$6,587.62 CR","Salary Symmetry Human R,Symmetry HR W 1299",NaN,$58.18
37,03 May 2023,"$7,291.18 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$703.56
38,04 Jan 2023,"$3,766.57 CR","Salary Symmetry Human R,Symmetry HR W 1215",NaN,$309.78
39,04 Jan 2023,"$4,734.49 CR","Salary Symmetry Human R,Symmetry HR W 1215",NaN,$967.92
40,26 Apr 2023,"$4,943.24 CR","Fast Transfer From A A LADEINDE,move balance",NaN,$0.94
41,26 Apr 2023,"$6,074.56 CR","Salary YNA,Payroll",NaN,"$1,131.32"

In [ ]:
merged_df_all6_1_2['New_Date'] = pd.to_datetime(merged_df_all6_1_2['New_Date'], format='%d %b %Y')

In [ ]:
merged_df_all6_1_2['New_Date'] = merged_df_all6_1_2['New_Date'].dt.strftime('%d-%b-%Y')

In [ ]:
merged_df_all6_1_2

,New_Date,Balance,Details,Debit,Credit
0,02-May-2023,"$2,517.55 CR","Direct Debit 314011 AGL TELCO,PAYWAY3466657131",68.00,NaN
1,02-May-2023,"$2,585.55 CR","International Transaction Fee,Value Date: 23/0...",4.83,NaN
2,02-May-2023,"$2,590.38 CR","Innovate1Pay Ltd Abuja NG NGA,106.00,Value Dat...",160.87,NaN
3,02-May-2023,"$2,751.25 CR","International Transaction Fee,Value Date: 23/0...",3.51,NaN
4,02-May-2023,"$2,754.76 CR","Innovate1Pay Ltd Abuja NG NGA,77.00,Value Date...",116.86,NaN
5,03-Jan-2023,"$3,456.79 CR","Direct Debit 314011 AGL TELCO,PAYWAY3379077714",68.00,NaN
6,03-Jan-2023,"$3,524.79 CR","Direct Debit 518073 Performance Educ,EZYPAYID ...","1,226.32",NaN
7,03-May-2023,"$3,100.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.45,NaN
8,04-May-2023,"$4,131.94 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",12.55,NaN
9,04-May-2023,"$4,144.49 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",46.69,NaN
10,04-May-2023,"$4,191.18 CR","AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,Card xx56...",100.00,NaN
11,04-May-2023,"$4,291.18 CR",Transfer to xx7964 CommBank app,"3,000.00",NaN
12,05-May-2023,"$3,112.68 CR","Direct Debit 348045 AGL SALES PTY LT,160009533332",109.59,NaN
13,05-May-2023,"$3,222.27 CR",SPOTTO VIC DARLINGHURST AU,34.32,NaN
14,05-May-2023,"$3,256.59 CR",Non CBA ATM Withdrawal Fee,2.80,NaN
15,05-May-2023,"$3,259.39 CR",Wdl ATM Red NP-Dandenong Mark Dandenong,200.00,NaN
16,05-May-2023,"$3,459.39 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",2.95,NaN
17,05-May-2023,"$3,462.34 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",9.60,NaN
18,05-May-2023,"$3,471.94 CR","TOY WAVERLEY MULGRAVE VI AUS,Card xx6241,Value...",660.00,NaN
19,06-Jan-2023,"$4,474.49 CR","Transfer To Driving School,CommBank App drivin...",260.00,NaN
20,06-May-2023,"$3,014.27 CR","BP DANDENONG 3940 DANDENONG VI AUS,Card xx5698...",98.41,NaN
21,10-Jan-2023,"$3,300.77 CR","Direct Debit 066429 Linkt Melbourne,70746973-7...",14.94,NaN
22,10-Jan-2023,"$3,315.71 CR","VICROADS CommBank app BPAY 2,528671080015065",864.40,NaN
23,10-Jan-2023,"$4,180.11 CR","VICROADS PAKENHAMEAST PAKENHAM AUS,Card xx6241...",294.38,NaN
24,11-Jan-2023,"$3,228.87 CR",PROUDS 132 MULGRAVE AU,71.90,NaN
25,27-Apr-2023,"$5,922.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78903",28.00,NaN
26,27-Apr-2023,"$5,950.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78904",28.00,NaN
27,27-Apr-2023,"$5,978.10 CR","AA CHADSTONE 0098 CHADSTONE VI AUS,Card xx5698...",96.46,NaN
28,28-Apr-2023,"$2,905.75 CR",Transfer to xx7964 CommBank app,"3,000.00",NaN
29,28-Apr-2023,"$5,905.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.35,NaN
30,29-Apr-2023,"$2,871.62 CR",SMP*Dominos Noble Park Noble Park03 AU,20.30,NaN
31,29-Apr-2023,"$2,891.92 CR","CellOPark Australia Matraville NS AUS,Card xx5...",13.83,NaN
32,03-May-2023,"$3,117.20 CR","Salary MONASH UNIVERSIT,SALARY 01163921",NaN,$599.65
33,03-May-2023,"$4,365.64 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,264.89"
34,03-May-2023,"$5,336.62 CR","Salary Yooralla,0009308",NaN,$970.98
35,03-May-2023,"$6,529.44 CR","Salary YNA,Payroll",NaN,"$1,192.82"
36,03-May-2023,"$6,587.62 CR","Salary Symmetry Human R,Symmetry HR W 1299",NaN,$58.18
37,03-May-2023,"$7,291.18 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$703.56
38,04-Jan-2023,"$3,766.57 CR","Salary Symmetry Human R,Symmetry HR W 1215",NaN,$309.78
39,04-Jan-2023,"$4,734.49 CR","Salary Symmetry Human R,Symmetry HR W 1215",NaN,$967.92
40,26-Apr-2023,"$4,943.24 CR","Fast Transfer From A A LADEINDE,move balance",NaN,$0.94
41,26-Apr-2023,"$6,074.56 CR","Salary YNA,Payroll",NaN,"$1,131.32"

In [ ]:
merged_df_all6_1_2.to_csv("statement3.csv")

In [ ]:
merged_df_all6_1_2['New_Date'] = pd.to_datetime(merged_df_all6_1_1['New_Date'], format='%d %b %Y')

In [ ]:
df_sorted_df_all6_1_2 = merged_df_all6_1_2.sort_values('New_Date')

In [ ]:
df_sorted_df_all6_1_2

,New_Date,Balance,Details,Debit,Credit
35,2022-07-01,"$6,529.44 CR","Salary YNA,Payroll",NaN,"$1,192.82"
36,2022-07-04,"$6,587.62 CR","Salary Symmetry Human R,Symmetry HR W 1299",NaN,$58.18
0,2022-07-05,"$2,517.55 CR","Direct Debit 314011 AGL TELCO,PAYWAY3466657131",68.00,NaN
1,2022-07-05,"$2,585.55 CR","International Transaction Fee,Value Date: 23/0...",4.83,NaN
37,2022-07-05,"$7,291.18 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$703.56
38,2022-07-06,"$3,766.57 CR","Salary Symmetry Human R,Symmetry HR W 1215",NaN,$309.78
2,2022-07-07,"$2,590.38 CR","Innovate1Pay Ltd Abuja NG NGA,106.00,Value Dat...",160.87,NaN
39,2022-07-07,"$4,734.49 CR","Salary Symmetry Human R,Symmetry HR W 1215",NaN,$967.92
10,2022-07-12,"$4,191.18 CR","AMAYSIM MOBILE PTY LTD SYDNEY NS AUS,Card xx56...",100.00,NaN
11,2022-07-12,"$4,291.18 CR",Transfer to xx7964 CommBank app,"3,000.00",NaN
8,2022-07-12,"$4,131.94 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",12.55,NaN
7,2022-07-12,"$3,100.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.45,NaN
6,2022-07-12,"$3,524.79 CR","Direct Debit 518073 Performance Educ,EZYPAYID ...","1,226.32",NaN
5,2022-07-12,"$3,456.79 CR","Direct Debit 314011 AGL TELCO,PAYWAY3379077714",68.00,NaN
9,2022-07-12,"$4,144.49 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",46.69,NaN
12,2022-07-13,"$3,112.68 CR","Direct Debit 348045 AGL SALES PTY LT,160009533332",109.59,NaN
14,2022-07-14,"$3,256.59 CR",Non CBA ATM Withdrawal Fee,2.80,NaN
16,2022-07-15,"$3,459.39 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",2.95,NaN
17,2022-07-15,"$3,462.34 CR","POST WAVERLEY GARDENS P VI AU,Card xx6241",9.60,NaN
18,2022-07-15,"$3,471.94 CR","TOY WAVERLEY MULGRAVE VI AUS,Card xx6241,Value...",660.00,NaN
29,2022-07-19,"$5,905.75 CR","KFC ASHBURTON ASHBURTON AU,Card xx5698",16.35,NaN
30,2022-07-19,"$2,871.62 CR",SMP*Dominos Noble Park Noble Park03 AU,20.30,NaN
28,2022-07-19,"$2,905.75 CR",Transfer to xx7964 CommBank app,"3,000.00",NaN
41,2023-01-11,"$6,074.56 CR","Salary YNA,Payroll",NaN,"$1,131.32"
3,2023-01-11,"$2,751.25 CR","International Transaction Fee,Value Date: 23/0...",3.51,NaN
40,2023-01-11,"$4,943.24 CR","Fast Transfer From A A LADEINDE,move balance",NaN,$0.94
4,2023-01-12,"$2,754.76 CR","Innovate1Pay Ltd Abuja NG NGA,77.00,Value Date...",116.86,NaN
13,2023-01-14,"$3,222.27 CR",SPOTTO VIC DARLINGHURST AU,34.32,NaN
15,2023-01-15,"$3,259.39 CR",Wdl ATM Red NP-Dandenong Mark Dandenong,200.00,NaN
20,2023-01-16,"$3,014.27 CR","BP DANDENONG 3940 DANDENONG VI AUS,Card xx5698...",98.41,NaN
21,2023-01-16,"$3,300.77 CR","Direct Debit 066429 Linkt Melbourne,70746973-7...",14.94,NaN
19,2023-01-16,"$4,474.49 CR","Transfer To Driving School,CommBank App drivin...",260.00,NaN
22,2023-01-17,"$3,315.71 CR","VICROADS CommBank app BPAY 2,528671080015065",864.40,NaN
24,2023-01-18,"$3,228.87 CR",PROUDS 132 MULGRAVE AU,71.90,NaN
23,2023-01-18,"$4,180.11 CR","VICROADS PAKENHAMEAST PAKENHAM AUS,Card xx6241...",294.38,NaN
27,2023-01-19,"$5,978.10 CR","AA CHADSTONE 0098 CHADSTONE VI AUS,Card xx5698...",96.46,NaN
26,2023-01-19,"$5,950.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78904",28.00,NaN
25,2023-01-19,"$5,922.10 CR","Direct Debit 017325 HACSU VIC #2,HACSU78903",28.00,NaN
31,2023-01-21,"$2,891.92 CR","CellOPark Australia Matraville NS AUS,Card xx5...",13.83,NaN
33,2023-01-22,"$4,365.64 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,264.89"
32,2023-01-22,"$3,117.20 CR","Salary MONASH UNIVERSIT,SALARY 01163921",NaN,$599.65
34,2023-01-24,"$5,336.62 CR","Salary Yooralla,0009308",NaN,$970.98

In [ ]:
df_sorted_df_all6_1_1

,New_Date,Balance,Details,Debit,Credit
35,2022-07-01,"$6,897.88 CR","Salary 9D Care,9D Care",NaN,$275.22
36,2022-07-04,"$6,998.48 CR","Direct Credit 074806 BUPA_CLM_CR-0407,C5703707...",NaN,$100.60
0,2022-07-05,"$6,780.80 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241",81.96,NaN
1,2022-07-05,"$6,835.77 CR","COSTCO WHOLESALE AUS MOORABBIN AIRAU,Card xx6241",162.71,NaN
37,2022-07-05,"$6,862.76 CR","Return COSTCO WHOLESALE AUS MOORABBI,Card xx6241",NaN,$26.99
38,2022-07-06,"$11,780.80 CR","Transfer From A A LADEINDE,Part of Professiona...",NaN,"$5,000.00"
2,2022-07-07,"$11,780.50 CR","OFFICEWORKS 0348 KEYSBOROUGH AU AUS,Card xx624...",0.3,NaN
39,2022-07-07,"$11,841.58 CR","Salary Nextt Health PL,1020773/07/2022",NaN,$61.08
11,2022-07-12,"$11,763.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da...",78.0,NaN
10,2022-07-12,"$11,745.58 CR","KMART 1226 CLAYTON AU AUS,Card xx6241,Value Da...",18.0,NaN
8,2022-07-12,"$11,700.56 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241",13.12,NaN
7,2022-07-12,"$11,682.79 CR","T C QUALITY MEATS DANDENONG VIC AU,Card xx6241",17.77,NaN
6,2022-07-12,"$11,666.51 CR",PREMIER POULTRY DANDEN DANDENONG AU,16.28,NaN
5,2022-07-12,"$11,647.06 CR","QANDI FRESH PTY LTD DANDENONG AU,Card xx6241",19.45,NaN
9,2022-07-12,"$11,713.68 CR","WOOLWORTHS 3806 CLAYTON AU AUS,Card xx6241,Val...",31.90,NaN
44,2022-07-13,"$15,016.78 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,"$1,605.62"
43,2022-07-13,"$13,411.16 CR","Salary Yooralla,0009308",NaN,$537.54
45,2022-07-13,"$15,708.16 CR","Salary HammondCare,20052",NaN,$694.06
42,2022-07-13,"$12,873.62 CR","Salary MONASH UNIVERSIT,SALARY 01163158",NaN,"$1,226.56"
12,2022-07-13,"$15,014.10 CR","Direct Debit 066429 Linkt Melbourne,48131845-7...",2.68,NaN
14,2022-07-14,"$11,465.29 CR","Transfer to xx7964 CommBank app,July sa","5,000.00",NaN
46,2022-07-14,"$16,465.29 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,$757.13
47,2022-07-15,"$12,210.37 CR","Salary 9D Care,9D Care",NaN,$817.96
18,2022-07-15,"$11,454.24 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05,NaN
17,2022-07-15,"$11,443.19 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05,NaN
16,2022-07-15,"$11,392.41 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx...",50.78,NaN
30,2022-07-19,"$10,559.37 CR","WPNP PTY LTD NetBank BPAY 304303,1635571282 rent","1,651.00",NaN
28,2022-07-19,"$10,478.06 CR","MON HLTH CLAY CPARK CLAYTON VI AUS,Card xx6241...",11.05,NaN
29,2022-07-19,"$10,489.11 CR","COLES EXPRESS 6805 NOBLE PARK N AU AUS,Card xx...",70.26,NaN
40,2023-01-11,"$10,846.41 CR","Direct Credit 621009 SmartSalary,GroupedSS",NaN,"$2,778.82"
41,2023-01-11,"$8,067.59 CR","Salary Symmetry Human R,Symmetry HR W 1221",NaN,$893.76
3,2023-01-11,"$5,846.41 CR",Transfer to xx7964 CommBank app,"5,000.00",NaN
4,2023-01-12,"$5,246.41 CR","Transfer To Regeneration Church,CommBank App 6...",600.00,NaN
13,2023-01-14,"$5,190.36 CR","AA OFFCR OTBND7020 OFFICER SOUTH VI AUS,Card x...",56.05,NaN
15,2023-01-15,"$5,155.36 CR",T*M Tickets-CSS - Sat,35.00,NaN
19,2023-01-16,"$5,000.86 CR","Direct Debit 507533 SOUTH EAST WATER,DT.1bqjog...",62.00,NaN
20,2023-01-16,"$5,062.86 CR",HENRYS MERCATO WAVER MULGRAVE AU,50.22,NaN
21,2023-01-16,"$5,113.08 CR",PAT'S MUSIC OAKLEIGH SOUTVICAU,42.28,NaN
22,2023-01-17,"$4,650.86 CR",ANDRE J MENSWEAR CLAYTON VICAU,350.00,NaN
49,2023-01-18,"$5,758.65 CR","Salary Symmetry Human R,Symmetry HR W 1227",NaN,$382.57
24,2023-01-18,"$4,048.48 CR","Direct Debit 000793 BUPA AUSTRALIA,46484796000...",602.38,NaN
23,2023-01-18,"$4,005.98 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",42.50,NaN
48,2023-01-18,"$5,376.08 CR","Salary Symmetry Human R,Symmetry HR W 1227",NaN,"$1,370.10"
25,2023-01-19,"$5,650.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership",28.00,NaN
27,2023-01-19,"$5,706.22 CR","Direct Debit 157640 RACV INSURANCE,MOT73949596...",52.43,NaN
26,2023-01-19,"$5,678.22 CR","Direct Debit 017325 HACSU VIC #2,HACSU Membership",28.00,NaN
31,2023-01-21,"$5,607.92 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx624...",42.30,NaN
33,2023-01-22,"$3,607.92 CR",Transfer to xx7964 CommBank app,"2,000.00",NaN
32,2023-01-22,"$1,957.02 CR","WPNP PTY LTD CommBank app BPAY 3,1635571282 rent","1,651.00",NaN
50,2023-01-22,"$3,608.02 CR","Fast Transfer From RENTPAY TECHNOLOGY PT,Accou...",NaN,$0.10
34,2023-01-24,"$1,924.32 CR","WOOLWORTHS 3130 WAVERLEY GDNS AU AU,Card xx569...",32.70,NaN

In [ ]:
df_sorted

In [ ]:
statement20222023 = pd.concat([ merged_df_all4 , merged_df_all6_1_1,merged_df_all6_1_2], ignore_index=True)

In [ ]:
statement20222023.to_csv('statement20222023.csv')